/**
 * AUTO-GENERATED by scripts/generate-capabilities.mjs (from the SAME schema
 * parse that emits apps/VoteTorrentDashboard/src/auth/capabilities.js) from
 * packages/vote-core/schema/votetorrent.qsql — do not hand-edit. Run
 * `yarn workspace votetorrent-dashboard capabilities:generate` after any
 * change to `view Scope` or a `.Scope = '<code>'` enforcement site, then
 * commit the result. capabilities.test.mjs's staleness check fails the build
 * if this file ever drifts from a fresh generation.
 *
 * Data-only, zero imports: this is the single source of truth for which
 * tables each capability's read helpers may query, consumed by
 * `packages/web-data`'s officer read modules to derive `TABLES_READ` "so
 * there is exactly one list" rather than a re-declared, driftable one.
 */

/** @typedef {'registrations'|'elections'|'ballotsQuestions'|'networkSettings'|'authorityProfile'|'authorityPeers'|'administrationOfficers'|'keyholders'|'inviteAuthorities'} CapabilityId */

/** @type {Readonly<Record<CapabilityId, ReadonlyArray<string>>>} */
export const CAPABILITY_TABLES = Object.freeze({
	registrations: Object.freeze(['Association', 'AssociationPrivate', 'AssociationRequest', 'AttestationChallenge', 'ElectionRegistrant', 'PollingDevice', 'Registrant', 'RegistrantPrivate', 'RegistrantPublic', 'RegistrantSelective', 'RegistrantSignatureTaskExtension', 'RegistrationBridgeKey', 'RegistrationRequest']),
	elections: Object.freeze(['Election', 'ElectionAttestationPolicy', 'ElectionDisclosurePolicy', 'ElectionRecordValidityPolicy', 'ElectionRegistrationField', 'ElectionRevision', 'ElectionRevisionSignatureTaskExtension', 'ElectionSignatureTaskExtension']),
	ballotsQuestions: Object.freeze(['Ballot', 'BallotSignatureTaskExtension', 'Option', 'Question']),
	networkSettings: Object.freeze(['Network', 'NetworkSignatureTaskExtension', 'ProposedNetwork']),
	authorityProfile: Object.freeze(['Authority', 'AuthoritySignatureTaskExtension']),
	authorityPeers: Object.freeze(['AuthorityPeer']),
	administrationOfficers: Object.freeze(['AdminSignatureTaskExtension']),
	keyholders: Object.freeze([]),
	inviteAuthorities: Object.freeze([]),
});
