/**
 * device-user.ts — Device identity resolution, hardware-key-provisioning aware
 * (D-01/D-09/D-12/D-14, Phase 49 hardware rewrite of the original Phase 16 module).
 *
 * BEFORE this rewrite: `getOrCreateDeviceUser` generated a plaintext secp256k1 keypair on first
 * call and persisted the `User` alongside its raw hex private key (a second field on the same
 * stored object) under `DEVICE_USER_KEY` in AsyncStorage — exactly the T-16-01 threat this phase
 * exists to remove (anyone holding an unlocked device, or extracting AsyncStorage from a rooted
 * device or an `adb backup`, could mint valid officer signatures).
 *
 * AFTER this rewrite: this module NEVER generates or persists private key material. The
 * hardware-backed P-256 keypair lives entirely inside the Android Keystore, generated by the
 * native `provisionDeviceKey` TurboModule method (`packages/attestation-native`, 49-04) via the
 * officer-facing `ProvisionSigningKeyScreen` (D-14, lands in 49-10). This module's role shrinks
 * to persisting/reading the resulting `User` row — never a key.
 *
 *   - `getDeviceUser()` — read-only. Returns `undefined` if the device has never been
 *     provisioned. `device-signer.ts` uses this to detect the `NO_KEY_PROVISIONED` case BEFORE
 *     any native call is attempted.
 *   - `persistProvisionedDeviceUser(displayName, publicKeyCompressedHex)` — called ONLY by the
 *     49-10 provisioning screen, after a real native `provisionDeviceKey` ceremony has already
 *     returned a real hardware-backed public key. Performs no key generation and no native call
 *     itself — pure persistence.
 *   - `getOrCreateDeviceUser(displayName)` — kept as a D-09 compatibility wrapper so every
 *     pre-existing call site keeps compiling. Despite its name it NO LONGER creates anything:
 *     hardware key generation requires an interactive biometric ceremony that cannot run
 *     silently at boot or from an arbitrary screen. See its own doc comment below.
 *
 * AUTH-01 compliance carries forward: any hex this module persists is already `bytesToHex`
 * -encoded before it arrives here (`publicKeyCompressedHex`, from the native bridge) — this
 * module itself no longer touches raw key bytes at all.
 *
 * T-16-01 (RESOLVED by this plan): the private key is no longer stored anywhere in JS —
 * plaintext or otherwise. It never leaves the Android Keystore. The one remaining plaintext
 * software key generator in this app is `dev-only-key-gen.ts`, referenced only via a
 * `__DEV__`-lexically-guarded `require()` below (D-12).
 */

import AsyncStorage from '@react-native-async-storage/async-storage'
import type { User } from '@votetorrent/vote-core'
import { UserKeyType } from '@votetorrent/vote-core'

/** AsyncStorage key under which `{ user: User }` is persisted (no key material, Phase 49). */
export const DEVICE_USER_KEY = 'deviceUser'

/**
 * AsyncStorage key under which the device provisioning record (49-16) is persisted — a SIBLING
 * key to `DEVICE_USER_KEY`, never a field folded into that blob. See
 * `DeviceProvisioningRecord`'s doc comment for why.
 */
export const DEVICE_PROVISIONING_KEY = 'deviceSigningProvisioning'

/**
 * AsyncStorage key under which the recovery-in-progress marker is persisted (49-14 follow-up:
 * `.planning/todos/pending/2026-08-18-interrupted-handlerecovery-keystore-metadata-desync.md`).
 *
 * **What this guards against:** `ProvisionSigningKeyScreen.tsx`'s `handleRecovery` performs two
 * state-mutating steps that are NOT atomic — (1) `provisionDeviceKey` regenerates the
 * Keystore-resident `SIGNING_KEY_ALIAS` private key, UNPROMPTED, no biometric/device-credential
 * gate; (2) later, `persistProvisionedDeviceUser` updates local storage so `activeKeys[0].key`
 * names the new public key. Any interruption between them (screen timeout, app kill, process
 * death) leaves the Keystore holding a new, never-registered private key while local storage
 * still names the old, invalidated public key — `device-signer.ts`'s `createDeviceSigner` then
 * signs with the NEW key while reporting the OLD one, which fails the schema's `SignatureValid`
 * CHECK with no actionable path back (the raw failure carries no `signWithDeviceKey` reject
 * `code`, so it bypasses the D-13 taxonomy entirely).
 *
 * **The prevention half of the fix:** `handleRecovery` writes this marker immediately after
 * `provisionDeviceKey` resolves (Keystore alias now regenerated) and clears it only once
 * `persistProvisionedDeviceUser` + `persistDeviceProvisioningRecord` both complete. While the
 * marker is present, `device-signer.ts`'s `createDeviceSigner` fails CLOSED with the existing
 * `KEY_INVALIDATED_REASSOCIATE` code — BEFORE any native signing call — rather than letting a
 * routine per-use signing action silently attempt (and schema-reject) a mismatched signature.
 *
 * **What this does NOT cover:** a device whose desync predates this marker's existence (the
 * interruption happened before this code shipped) — no marker was ever written for it. That
 * device's rescue path is the SEPARATE, message-based `isSignatureDesyncError` classification in
 * `deviceSigningError.ts`, which recognizes the resulting `SignatureValid` CHECK failure itself
 * and routes the officer back into `handleRecovery` regardless of marker state — `handleRecovery`
 * re-running is self-healing either way, since it always re-derives the currently-registered
 * network key from a fresh `getSummary()` read (never from local storage) and unconditionally
 * overwrites local storage at the end.
 */
export const DEVICE_RECOVERY_IN_PROGRESS_KEY = 'deviceSigningRecoveryInProgress'

/** Ten years in milliseconds — expiration epoch for the provisioned device key. */
const TEN_YEARS_MS = 10 * 365 * 24 * 60 * 60 * 1000

interface StoredDeviceUser {
	user: User
}

/**
 * The device-local provisioning artifact captured at the end of a completed 49-04
 * `provisionDeviceKey` ceremony (49-16, D-08/D-15b).
 *
 * **Why this is a separate AsyncStorage key, not extra fields on `deviceUser`:** two consumers
 * constrain the `deviceUser` blob's shape today — `device-signer.ts` reads
 * `user.activeKeys[0].key` as the `signerKey` it attributes every signature to, and
 * `networks-engine.create()` (`packages/vote-engine/src/networks/networks-engine.ts`) reads
 * `user.activeKeys?.[0]` as the founding `UserKey` it writes through its bootstrap branch.
 * Putting the recovery key into `activeKeys[1]` would be invisible to both today and a live
 * hazard the moment either starts iterating over `activeKeys`; putting a cert chain inside the
 * `User` object would change the shape those two read. A sibling key costs nothing and keeps
 * both invariants provable.
 *
 * **What this is for:** `certificateChainBase64` is the **D-08/D-15b artifact** — captured but
 * unconsumed by any verifier in this phase, persisted so that D-15b's "leaf + intermediates, no
 * root" shape claim has something on disk to inspect at all (49-13 recorded D-15b as
 * NOT-EXERCISED precisely because nothing was ever written).
 *
 * **T-49-PLAIN:** every field here is PUBLIC certificate/key material. This record must never
 * carry a private key, a raw signature, or any other secret — only compressed public keys and
 * base64-encoded certificate bytes.
 */
export interface DeviceProvisioningRecord {
	/** Compressed SEC1 public key (hex) of the device's D-16 recovery key. */
	recoveryPublicKeyCompressedHex: string
	/** Compressed SEC1 public key (hex) of the attested signing key — public material only. */
	attestedPublicKeyCompressedHex: string
	/** The stable Keystore alias the attested key was generated under. */
	signingKeyAlias: string
	/** Leaf + intermediate certs (base64 DER), no root — the D-08/D-15b shape claim. */
	certificateChainBase64: string[]
	/** `Date.now()` at capture time. */
	capturedAt: number
}

/**
 * Return the persisted device `User`, or `undefined` if the device has never been provisioned.
 * Read-only — never generates or persists anything. `device-signer.ts` calls this to detect the
 * `NO_KEY_PROVISIONED` case before any native call is attempted.
 *
 * Tolerates (without reading) a leftover raw-key field from a pre-Phase-49 install: this
 * function only ever reads `.user` off the parsed blob, so an old plaintext-key entry still
 * resolves the same `User` it always did — the stray key material is simply never touched, and
 * the next `persistProvisionedDeviceUser` call overwrites the whole entry with the new,
 * key-material-free shape.
 */
export async function getDeviceUser(): Promise<User | undefined> {
	const stored = await AsyncStorage.getItem(DEVICE_USER_KEY)
	if (stored === null) return undefined
	const parsed = JSON.parse(stored) as StoredDeviceUser
	return parsed.user
}

/**
 * Persist a device `User` built from a REAL, already-provisioned hardware public key. Called
 * ONLY by the 49-10 `ProvisionSigningKeyScreen`, after its own successful native
 * `provisionDeviceKey` ceremony — this function performs no key generation and no native call
 * itself; it is pure persistence.
 *
 * @param publicKeyCompressedHex - the 33-byte compressed SEC1 point, hex-encoded, from
 *   `provisionDeviceKey`'s `publicKeyCompressedHex` field (49-04). NEVER the sibling SPKI-DER
 *   public-key field on that same bridge response — that encoding is not a valid
 *   `UserKey.PubKey` (RESEARCH Pattern 4), and registering it as one fails closed (and silently,
 *   per `verify()`'s swallow-all exception handling).
 */
export async function persistProvisionedDeviceUser(
	displayName: string,
	publicKeyCompressedHex: string,
): Promise<User> {
	// Hermes (RN 0.78+) exposes crypto.randomUUID() at runtime; cast to satisfy the app's TS
	// config, which omits the dom lib declarations.
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	const userId: string = (globalThis as any).crypto.randomUUID()
	const user: User = {
		id: userId,
		name: displayName,
		activeKeys: [
			{
				key: publicKeyCompressedHex,
				// D-03/D-04: the hardware Keystore key is permanently P-256 (secp256r1) —
				// Android Keystore cannot hold a secp256k1 key.
				type: UserKeyType.p256,
				expiration: Date.now() + TEN_YEARS_MS,
			},
		],
	}

	const entry: StoredDeviceUser = { user }
	await AsyncStorage.setItem(DEVICE_USER_KEY, JSON.stringify(entry))

	return user
}

/**
 * D-09 compatibility wrapper — kept so every pre-existing call site (screens that need `User`
 * for display/id purposes, `AppProvider.tsx`'s boot re-attach) keeps compiling unchanged.
 *
 * Despite the name, this NO LONGER creates anything: hardware key generation requires an
 * interactive biometric ceremony (`ProvisionSigningKeyScreen`, D-14/49-10) that cannot run
 * silently at boot or from an arbitrary screen — the exact silent-plaintext-generation behavior
 * this plan removes. On an already-provisioned device (including one carrying a pre-Phase-49
 * raw-key blob) this is equivalent to `getDeviceUser()`. On a genuinely unprovisioned device it
 * rejects with a `code: 'NO_KEY_PROVISIONED'`-tagged error (49-16) — the same code
 * `device-signer.ts` attaches for the identical condition — so this is now a ROUTABLE
 * condition: `isDeviceSigningError` recognizes it, and call sites (e.g. `AddNetworkScreen`,
 * 49-16) route it through the shared `useDeviceSigningErrorHandler` hook to the provisioning
 * screen rather than falling through to raw-message handling.
 *
 * This is a deliberate, temporary consequence of D-12/D-14, not a bug: until 49-10 lands the
 * provisioning screen, a genuinely fresh install cannot proceed past a call site that needs a
 * device user. Removing silent plaintext key generation necessarily removes the silent fallback
 * that depended on it.
 */
export async function getOrCreateDeviceUser(displayName: string): Promise<User> {
	const user = await getDeviceUser()
	if (user) return user
	const err = new Error(
		`getOrCreateDeviceUser: no device signing key provisioned for "${displayName}" — hardware ` +
			'key provisioning requires the biometric ProvisionSigningKeyScreen ceremony (D-14).',
	) as Error & { code: string }
	err.code = 'NO_KEY_PROVISIONED'
	throw err
}

/**
 * Persist the device provisioning record captured at the end of a completed 49-04
 * `provisionDeviceKey` ceremony (D-08/D-15b). Pure persistence: no native calls, no key
 * generation, no derivation. See `DeviceProvisioningRecord`'s doc comment for the shape contract
 * and why this lives under its own AsyncStorage key rather than on `deviceUser`.
 */
export async function persistDeviceProvisioningRecord(
	record: DeviceProvisioningRecord,
): Promise<void> {
	await AsyncStorage.setItem(DEVICE_PROVISIONING_KEY, JSON.stringify(record))
}

/**
 * Read the device provisioning record, or `undefined` if none has ever been written. Pure
 * persistence — no native calls.
 */
export async function getDeviceProvisioningRecord(): Promise<DeviceProvisioningRecord | undefined> {
	const stored = await AsyncStorage.getItem(DEVICE_PROVISIONING_KEY)
	if (stored === null) return undefined
	return JSON.parse(stored) as DeviceProvisioningRecord
}

/**
 * Mark that `handleRecovery` has regenerated the `SIGNING_KEY_ALIAS` Keystore entry but has not
 * yet completed the paired local-metadata write that would bring it back in sync (49-14
 * follow-up). See `DEVICE_RECOVERY_IN_PROGRESS_KEY`'s doc comment for the full rationale.
 */
export async function markRecoveryInProgress(): Promise<void> {
	await AsyncStorage.setItem(DEVICE_RECOVERY_IN_PROGRESS_KEY, JSON.stringify({ startedAt: Date.now() }))
}

/**
 * Clear the recovery-in-progress marker. Called ONLY once BOTH `persistProvisionedDeviceUser`
 * and `persistDeviceProvisioningRecord` have completed at the end of a full `handleRecovery` run
 * — never earlier, and never on a caught/interrupted path (leaving the marker set on failure is
 * the entire point: it is what makes the next routine signing attempt fail closed instead of
 * silently producing a schema-invalid signature).
 */
export async function clearRecoveryInProgress(): Promise<void> {
	await AsyncStorage.removeItem(DEVICE_RECOVERY_IN_PROGRESS_KEY)
}

/**
 * Read-only check used by `device-signer.ts`'s `createDeviceSigner` — every one of this app's
 * ~22 routine per-use signing call sites — BEFORE any native signing call is attempted. `true`
 * means a `handleRecovery` run regenerated the Keystore alias but never finished re-syncing local
 * metadata; the caller must fail closed rather than risk signing with a key that no longer
 * matches the `signerKey` local storage would report.
 */
export async function isRecoveryInProgress(): Promise<boolean> {
	const stored = await AsyncStorage.getItem(DEVICE_RECOVERY_IN_PROGRESS_KEY)
	return stored !== null
}

/**
 * D-12 dev-only escape hatch: returns a plaintext software keypair, but ONLY inside a literal
 * `if (__DEV__)` block whose `require()` is lexically nested inside it — the ONE shape Metro's
 * minifier actually eliminates from a release build (RESEARCH Pitfall 4). This is a CommonJS
 * `require()`, never an ES `import` — an ES `import` is hoisted and unconditional regardless of
 * any runtime guard placed around its use, which is exactly the `registrant-dev-seed.ts`
 * counter-example this repo already carries a WR-11 correction for.
 *
 * `device-user.ts` is itself statically imported by every one of this app's ~22 signing call
 * sites, so THIS is the file the guard must live in — a guard one level up (e.g. in a caller)
 * would not prevent Metro from bundling `dev-only-key-gen.ts` if this file imported it
 * unconditionally.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- the return shape (a hex keypair)
// deliberately is NOT spelled out here via an explicit type or a type-only import of the
// dev-only module: either would put a literal reference to that module's shape in this file's
// source text, and this file's own release-guard test asserts NO import statement of any kind
// references `dev-only-key-gen` — only the single lexically-guarded `require()` below may.
export function generateSoftwareKeyForDev(): any {
	if (__DEV__) {
		// eslint-disable-next-line @typescript-eslint/no-var-requires -- deliberate lazy,
		// __DEV__-lexically-guarded require — see the function doc comment above (D-12).
		const { generateSoftwareDeviceKey } = require('./dev-only-key-gen')
		return generateSoftwareDeviceKey()
	}
	throw new Error('generateSoftwareKeyForDev: must never run outside __DEV__ (D-12)')
}
