/**
 * AUTO-GENERATED by scripts/generate-capabilities.mjs from
 * packages/vote-core/schema/votetorrent.qsql — do not hand-edit. Run
 * `yarn workspace votetorrent-dashboard capabilities:generate` after any
 * change to `view Scope` or a `.Scope = '<code>'` enforcement site, then
 * commit the result. test/node/capabilities.test.mjs's staleness check fails
 * the build if this file ever drifts from a fresh generation.
 *
 * `tier` is derived, not typed: `sites > 0 ? 1 : 2`. Tier 2 means the scope
 * has ZERO schema enforcement sites and is checked entirely in TypeScript by
 * `context.Is*Valid` booleans inside authority-engine.ts — a client that
 * talks to the raw Quereus Database handle instead of going through
 * vote-engine loses that enforcement silently. 'keyholders' ('ik') and
 * 'inviteAuthorities' ('iad') are the two tier-2 capabilities below.
 */

/** @typedef {'rn'|'rad'|'vrg'|'iad'|'uai'|'ceb'|'mel'|'cap'|'ik'} ScopeCode */

/** @typedef {'registrations'|'elections'|'ballotsQuestions'|'networkSettings'|'authorityProfile'|'authorityPeers'|'administrationOfficers'|'keyholders'|'inviteAuthorities'} CapabilityId */

/**
 * @typedef {object} Capability
 * @property {CapabilityId} id
 * @property {ScopeCode} scope
 * @property {string} schemaName
 * @property {1 | 2} tier
 * @property {number} sites
 * @property {string[]} tables
 * @property {string | null} siteCountCaveat
 * @property {string} icon
 * @property {'electionOperations' | 'authorityAdministration'} group
 * @property {number} order
 * @property {string} titleKey
 * @property {string} emptyKey
 */

/** @type {ReadonlyArray<Capability>} */
export const CAPABILITIES = Object.freeze([
	Object.freeze({
		id: 'registrations',
		scope: 'vrg',
		schemaName: 'Validate registrations',
		tier: 1,
		sites: 18,
		tables: ['Association', 'AssociationPrivate', 'AssociationRequest', 'AttestationChallenge', 'ElectionRegistrant', 'PollingDevice', 'Registrant', 'RegistrantPrivate', 'RegistrantPublic', 'RegistrantSelective', 'RegistrantSignatureTaskExtension', 'RegistrationBridgeKey', 'RegistrationRequest'],
		siteCountCaveat: null,
		icon: '👥',
		group: 'electionOperations',
		order: 1,
		titleKey: 'panels.registrations.title',
		emptyKey: 'panels.registrations.empty',
	}),
	Object.freeze({
		id: 'elections',
		scope: 'mel',
		schemaName: 'Manage Elections',
		tier: 1,
		sites: 12,
		tables: ['Election', 'ElectionAttestationPolicy', 'ElectionDisclosurePolicy', 'ElectionRecordValidityPolicy', 'ElectionRegistrationField', 'ElectionRevision', 'ElectionRevisionSignatureTaskExtension', 'ElectionSignatureTaskExtension'],
		siteCountCaveat: null,
		icon: '🗳',
		group: 'electionOperations',
		order: 2,
		titleKey: 'panels.elections.title',
		emptyKey: 'panels.elections.empty',
	}),
	Object.freeze({
		id: 'ballotsQuestions',
		scope: 'ceb',
		schemaName: 'Create/Edit ballot templates',
		tier: 1,
		sites: 7,
		tables: ['Ballot', 'BallotSignatureTaskExtension', 'Option', 'Question'],
		siteCountCaveat: null,
		icon: '📋',
		group: 'electionOperations',
		order: 3,
		titleKey: 'panels.ballotsQuestions.title',
		emptyKey: 'panels.ballotsQuestions.empty',
	}),
	Object.freeze({
		id: 'networkSettings',
		scope: 'rn',
		schemaName: 'Revise Network',
		tier: 1,
		sites: 3,
		tables: ['Network', 'NetworkSignatureTaskExtension', 'ProposedNetwork'],
		siteCountCaveat: null,
		icon: '🌐',
		group: 'authorityAdministration',
		order: 4,
		titleKey: 'panels.networkSettings.title',
		emptyKey: 'panels.networkSettings.empty',
	}),
	Object.freeze({
		id: 'authorityProfile',
		scope: 'uai',
		schemaName: 'Update Authority Information',
		tier: 1,
		sites: 2,
		tables: ['Authority', 'AuthoritySignatureTaskExtension'],
		siteCountCaveat: null,
		icon: '🏛',
		group: 'authorityAdministration',
		order: 5,
		titleKey: 'panels.authorityProfile.title',
		emptyKey: 'panels.authorityProfile.empty',
	}),
	Object.freeze({
		id: 'authorityPeers',
		scope: 'cap',
		schemaName: 'Configure Authority Peers',
		tier: 1,
		sites: 2,
		tables: ['AuthorityPeer'],
		siteCountCaveat: null,
		icon: '🖧',
		group: 'authorityAdministration',
		order: 6,
		titleKey: 'panels.authorityPeers.title',
		emptyKey: 'panels.authorityPeers.empty',
	}),
	Object.freeze({
		id: 'administrationOfficers',
		scope: 'rad',
		schemaName: 'Revise or replace the Admin',
		tier: 1,
		sites: 1,
		tables: ['AdminSignatureTaskExtension'],
		siteCountCaveat: 'This site count reflects only the `AdminSigning.Scope = \'rad\'` idiom this generator\'s `.Scope = \'<code>\'` pattern can match. The real enforcement site for \'rad\' uses a different idiom, `json_each(O.Scopes) where value = \'rad\'` inside `Admin.OfficerRequired`, which this extractor cannot see. Treat this number as an undercount, not the true site count.',
		icon: '⚖️',
		group: 'authorityAdministration',
		order: 7,
		titleKey: 'panels.administrationOfficers.title',
		emptyKey: 'panels.administrationOfficers.empty',
	}),
	Object.freeze({
		id: 'keyholders',
		scope: 'ik',
		schemaName: 'Invite Keyholders',
		tier: 2,
		sites: 0,
		tables: [],
		siteCountCaveat: null,
		icon: '🔑',
		group: 'authorityAdministration',
		order: 8,
		titleKey: 'panels.keyholders.title',
		emptyKey: 'panels.keyholders.empty',
	}),
	Object.freeze({
		id: 'inviteAuthorities',
		scope: 'iad',
		schemaName: 'Invite other Authorities',
		tier: 2,
		sites: 0,
		tables: [],
		siteCountCaveat: null,
		icon: '🤝',
		group: 'authorityAdministration',
		order: 9,
		titleKey: 'panels.inviteAuthorities.title',
		emptyKey: 'panels.inviteAuthorities.empty',
	})
]);

/**
 * @typedef {object} PanelGroup
 * @property {'electionOperations' | 'authorityAdministration'} id
 * @property {string} titleKey
 */

/** @type {ReadonlyArray<PanelGroup>} */
export const PANEL_GROUPS = Object.freeze([
	Object.freeze({ id: 'electionOperations', titleKey: 'nav.groupElectionOperations' }),
	Object.freeze({ id: 'authorityAdministration', titleKey: 'nav.groupAuthorityAdministration' }),
]);

/** @type {ReadonlyArray<ScopeCode>} */
export const SCOPE_CODES = Object.freeze([
	'rn',
	'rad',
	'vrg',
	'iad',
	'uai',
	'ceb',
	'mel',
	'cap',
	'ik',
]);
