/**
 * association-attestation-policy.spec.ts — Phase 45-07 mocha/chai regression guard for the
 * election-terms attestation policy branch (D-14c, Assumption A5) and the minimal
 * AssociationPrivate device-uniqueness invariant (D-14e) on the non-attested path.
 *
 * Covers:
 *   - D-14c skip-verify: AttestationRequired=0 -> associate() succeeds even with a verifier
 *     whose verify() THROWS if ever invoked (the throw would be the proof it ran).
 *   - D-14c call-verify: AttestationRequired=1 -> associate() runs the REAL PlayIntegrityVerifier
 *     (Phase 43 synthetic-fixture harness, mirroring authority-transport.spec.ts) — a positive
 *     (accepted) case plus three negatives (wrong-nonce / tampered-jwe / Software security level)
 *     that all make associate() throw.
 *   - Assumption A5 fail-closed: no ElectionAttestationPolicy row for the election ->
 *     associate() still invokes verify() (proved by the throw-if-called sentinel) — absence of
 *     configuration defaults to REQUIRED, never an open hole.
 *   - D-14e: the non-attested (AttestationRequired=0) path still writes a minimal
 *     AssociationPrivate row, and device-uniqueness (DeviceId collision across registrants) holds
 *     identically on that path — a second registrant reusing the same DeviceId is rejected.
 *
 * NOT jest/mocha-coverable — deferred to 45-09's on-device Pixel 8 proof per 45-VALIDATION.md's
 * Manual-Only table (threat T-45-02 mitigation, made explicit here so the false-positive
 * boundary — "jest green" vs "device broken" — is documented at the point a reader would assume
 * this suite proves more than it does):
 *   - Real StrongBox/TEE hardware key generation and biometric-gated per-use signing (all key
 *     material here is Node-synthetic, generated by the Phase 43 fixtures, never a real Keystore).
 *   - `KeyPermanentlyInvalidatedException` on biometric-enrollment change (D-13) — no real
 *     Android Keystore in this runtime to invalidate.
 *   - `ADD COLUMN` re-attach safety for the schema changes this phase's plans introduced.
 *   - The D-16b Digest() module-load probe running on REAL Hermes (this suite runs on Node;
 *     `real-attestation-producer.test.ts` covers the probe's CONTRACT shape under jest/Node only).
 *   - The `EXPECTED_APP_PACKAGE` app-identity check against a REAL Play Integrity token from a
 *     REAL device (this suite's synthetic JWE/JWS tokens are Node-fabricated).
 */

import { expect } from 'chai'
import { secp256k1 } from '@noble/curves/secp256k1.js'
import { bytesToHex, hexToBytes } from '@noble/curves/utils.js'
import { SecurityLevel } from '@peculiar/asn1-android'
import type { AttestationVerification, DeviceAttestation, IAttestationVerifier, Signature } from '@votetorrent/vote-core'
import { AssociationEngine } from '../src/association/association-engine.js'
import { RegistrationEngine } from '../src/registration/registration-engine.js'
import { PlayIntegrityVerifier } from '../src/association/play-integrity-verifier.js'
import type { IIntegrityKeyProvider } from '../src/association/key-provider.js'
import { createTestNetwork, addTestAuthority, addTestElection } from './fixtures/test-context.js'
import { randomTestKeyPair } from './fixtures/keys.js'
import { generateSyntheticJweKeyMaterial, SYNTHETIC_EXPECTED_APP_IDENTITY } from './fixtures/attestation/synthetic-jwe.js'
import { generateTestRootCa } from './fixtures/attestation/test-root-ca.js'
import { buildSyntheticDeviceAttestation } from './fixtures/attestation/synthetic-device-attestation.js'
import { generateAndroidDeviceKeyPair } from './fixtures/attestation/synthetic-key-description.js'
import type { TestAuthorityContext } from './fixtures/test-context.js'
import type { EngineContext } from '../src/types.js'

// ---------------------------------------------------------------------------
// Fixture helpers — mirror association.spec.ts's small self-contained
// versions verbatim (that file's own module scope does not export them).
// ---------------------------------------------------------------------------

/** Build a real secp256k1 sign callback (@noble/curves v2 defaults — prehash:true). */
function makeRealSigner (userId: string): { sign: (digest: Uint8Array) => Promise<Signature> } {
  const { privateHex, publicHex } = randomTestKeyPair()
  const privBytes = hexToBytes(privateHex)
  const sign = async (digest: Uint8Array): Promise<Signature> => {
    const sig = secp256k1.sign(digest, privBytes) // v2 default: prehash:true
    return { signerUserId: userId, signerKey: publicHex, signature: bytesToHex(sig) }
  }
  return { sign }
}

let registrantSeq = 0
function nextRegistrantId (): string {
  registrantSeq += 1
  return `assoc-policy-registrant-${Date.now()}-${registrantSeq}`
}

let deviceSeq = 0
function nextDeviceKey (): string {
  deviceSeq += 1
  return `assoc-policy-device-key-${Date.now()}-${deviceSeq}`
}

const FUTURE_REGISTRANT_EXPIRATION = Date.now() + 365 * 86_400_000
const FUTURE_CHALLENGE_EXPIRATION = new Date(Date.now() + 10 * 60_000).toISOString()

function makeDeviceAttestation (overrides?: Partial<DeviceAttestation>): DeviceAttestation {
  deviceSeq += 1
  return {
    publicKey: `assoc-policy-device-pubkey-${deviceSeq}`,
    deviceId: `assoc-policy-device-id-${Date.now()}-${deviceSeq}`,
    attestationTime: Date.now(),
    certificateChain: ['cert-a', 'cert-b'],
    ...overrides
  }
}

/** Resolve the single Election row seeded by addTestElection() for this authority (mirrors association.spec.ts). */
async function resolveElectionId (ctx: EngineContext, authorityId: string): Promise<string> {
  const row = await ctx.db
    .prepare('select Id from Election where AuthorityId = :authorityId limit 1')
    .get({ authorityId })
  if (!row) throw new Error('resolveElectionId: Election not found for authority')
  return row.Id as string
}

/** Seed an active Registrant (Status='a') AND an Election, returning both plus the resolved electionId. */
async function setupAssociationTest (): Promise<{
  auth: TestAuthorityContext
  registrantId: string
  registrationEngine: RegistrationEngine
  sign: (digest: Uint8Array) => Promise<Signature>
  electionId: string
}> {
  const net = await createTestNetwork()
  const auth = await addTestAuthority(net)
  const { sign } = makeRealSigner(auth.user.id)
  const registrationEngine = new RegistrationEngine(auth.ctx)
  const registrantId = nextRegistrantId()
  await registrationEngine.createRegistrant(
    { id: registrantId, authorityId: auth.authority.id, privateCid: 'assoc-policy-test-private-cid-placeholder', expiration: FUTURE_REGISTRANT_EXPIRATION },
    sign
  )
  const elec = await addTestElection(auth)
  const electionId = await resolveElectionId(elec.ctx, elec.authority.id)
  return { auth, registrantId, registrationEngine, sign, electionId }
}

/** A verifier that ALWAYS throws — proves whether verify() was ever invoked at all. */
const throwIfCalledVerifier: IAttestationVerifier = {
  async verify (): Promise<AttestationVerification> {
    throw new Error('verify() must not run on the non-attested (AttestationRequired=0) path — D-14c')
  }
}

/** Build the REAL PlayIntegrityVerifier exactly as authority-transport.spec.ts does. */
async function buildRealVerifier (): Promise<{ verifier: PlayIntegrityVerifier, jweKeys: Awaited<ReturnType<typeof generateSyntheticJweKeyMaterial>>, testRoot: Awaited<ReturnType<typeof generateTestRootCa>> }> {
  const jweKeys = await generateSyntheticJweKeyMaterial()
  const testRoot = await generateTestRootCa()
  const keyProvider: IIntegrityKeyProvider = {
    getDecryptionKey: async () => jweKeys.decryptionKey,
    getVerificationKey: async () => jweKeys.verificationPublicKey
  }
  const verifier = new PlayIntegrityVerifier(keyProvider, [new Uint8Array(testRoot.cert.rawData)], SYNTHETIC_EXPECTED_APP_IDENTITY)
  return { verifier, jweKeys, testRoot }
}

// ===========================================================================
// D-14c: AttestationRequired policy branch (skip / call / fail-closed)
// ===========================================================================

describe('associate() — election-terms attestation policy gate (D-14c, Assumption A5)', () => {
  describe('AttestationRequired=0: verify() is SKIPPED', () => {
    it('associate() SUCCEEDS with a throw-if-called verifier and writes exactly one Association row', async () => {
      const { auth, registrantId, registrationEngine, sign, electionId } = await setupAssociationTest()
      await registrationEngine.setElectionAttestationPolicy(electionId, false, sign)

      const engine = new AssociationEngine(auth.ctx, throwIfCalledVerifier)
      const deviceKey = nextDeviceKey()
      const challenge = await engine.issueAttestationChallenge(registrantId, deviceKey, FUTURE_CHALLENGE_EXPIRATION, sign, electionId)
      const attestation = makeDeviceAttestation()

      // Resolving (not throwing) is itself the proof — the sentinel verifier would have
      // thrown if associate() had called verify() at all.
      await engine.associate({ registrantId, deviceKey, nonce: challenge.nonce, attestation }, sign)

      const row = await auth.ctx.db
        .prepare('select count(*) as n from Association where RegistrantId = :registrantId and DeviceKey = :deviceKey')
        .get({ registrantId, deviceKey })
      expect(Number(row?.n)).to.equal(1)
    })
  })

  describe('AttestationRequired=1: verify() is CALLED (real PlayIntegrityVerifier)', () => {
    it('positive: a default (accepted) synthetic DeviceAttestation makes associate() succeed', async () => {
      const { auth, registrantId, registrationEngine, sign, electionId } = await setupAssociationTest()
      await registrationEngine.setElectionAttestationPolicy(electionId, true, sign)
      const { verifier, jweKeys, testRoot } = await buildRealVerifier()

      const engine = new AssociationEngine(auth.ctx, verifier)
      // 51-02: verifyKeyAttestation's leaf-pubkey binding check (4b-2) requires
      // the leaf certificate's embedded public key to equal challenge.deviceKey
      // — use a real generated keypair + its SPKI-base64 encoding, and embed
      // that SAME keypair in the synthetic chain, rather than an opaque
      // `nextDeviceKey()` string.
      const { keyPair, deviceKeySpkiBase64: deviceKey } = await generateAndroidDeviceKeyPair()
      const challenge = await engine.issueAttestationChallenge(registrantId, deviceKey, FUTURE_CHALLENGE_EXPIRATION, sign, electionId)
      const attestation = await buildSyntheticDeviceAttestation({ challenge, jweKeys, testRoot, overrides: { leafKeyPair: keyPair } })

      await engine.associate({ registrantId, deviceKey, nonce: challenge.nonce, attestation }, sign)

      const row = await auth.ctx.db
        .prepare('select count(*) as n from Association where RegistrantId = :registrantId and DeviceKey = :deviceKey')
        .get({ registrantId, deviceKey })
      expect(Number(row?.n)).to.equal(1)
    })

    it('negative (wrong-nonce, D-06 relay attempt): associate() THROWS', async () => {
      const { auth, registrantId, registrationEngine, sign, electionId } = await setupAssociationTest()
      await registrationEngine.setElectionAttestationPolicy(electionId, true, sign)
      const { verifier, jweKeys, testRoot } = await buildRealVerifier()

      const engine = new AssociationEngine(auth.ctx, verifier)
      const deviceKey = nextDeviceKey()
      const challenge = await engine.issueAttestationChallenge(registrantId, deviceKey, FUTURE_CHALLENGE_EXPIRATION, sign, electionId)
      const attestation = await buildSyntheticDeviceAttestation({
        challenge,
        jweKeys,
        testRoot,
        overrides: { payloadNonce: 'this-is-not-the-bound-digest' }
      })

      let threw = false
      try {
        await engine.associate({ registrantId, deviceKey, nonce: challenge.nonce, attestation }, sign)
      } catch {
        threw = true
      }
      expect(threw, 'expected a wrong-nonce attestation to be rejected').to.be.true
    })

    it('negative (tampered JWE ciphertext): associate() THROWS', async () => {
      const { auth, registrantId, registrationEngine, sign, electionId } = await setupAssociationTest()
      await registrationEngine.setElectionAttestationPolicy(electionId, true, sign)
      const { verifier, jweKeys, testRoot } = await buildRealVerifier()

      const engine = new AssociationEngine(auth.ctx, verifier)
      const deviceKey = nextDeviceKey()
      const challenge = await engine.issueAttestationChallenge(registrantId, deviceKey, FUTURE_CHALLENGE_EXPIRATION, sign, electionId)
      const attestation = await buildSyntheticDeviceAttestation({
        challenge,
        jweKeys,
        testRoot,
        overrides: { jwe: { tamperCiphertext: true } }
      })

      let threw = false
      try {
        await engine.associate({ registrantId, deviceKey, nonce: challenge.nonce, attestation }, sign)
      } catch {
        threw = true
      }
      expect(threw, 'expected a tampered-ciphertext attestation to be rejected').to.be.true
    })

    it('negative (Software-only key attestation, D-02 balanced bar): associate() THROWS', async () => {
      const { auth, registrantId, registrationEngine, sign, electionId } = await setupAssociationTest()
      await registrationEngine.setElectionAttestationPolicy(electionId, true, sign)
      const { verifier, jweKeys, testRoot } = await buildRealVerifier()

      const engine = new AssociationEngine(auth.ctx, verifier)
      const deviceKey = nextDeviceKey()
      const challenge = await engine.issueAttestationChallenge(registrantId, deviceKey, FUTURE_CHALLENGE_EXPIRATION, sign, electionId)
      const attestation = await buildSyntheticDeviceAttestation({
        challenge,
        jweKeys,
        testRoot,
        overrides: { securityLevel: SecurityLevel.software }
      })

      let threw = false
      try {
        await engine.associate({ registrantId, deviceKey, nonce: challenge.nonce, attestation }, sign)
      } catch {
        threw = true
      }
      expect(threw, 'expected a Software-only key attestation to be rejected').to.be.true
    })
  })

  describe('no ElectionAttestationPolicy row (unconfigured election): fail-closed (Assumption A5)', () => {
    it('associate() THROWS via the throw-if-called sentinel — absence of a policy row defaults to attestation REQUIRED', async () => {
      const { auth, registrantId, sign, electionId } = await setupAssociationTest()
      // Deliberately no setElectionAttestationPolicy call for electionId — no row exists.

      const engine = new AssociationEngine(auth.ctx, throwIfCalledVerifier)
      const deviceKey = nextDeviceKey()
      const challenge = await engine.issueAttestationChallenge(registrantId, deviceKey, FUTURE_CHALLENGE_EXPIRATION, sign, electionId)
      const attestation = makeDeviceAttestation()

      let threw = false
      try {
        await engine.associate({ registrantId, deviceKey, nonce: challenge.nonce, attestation }, sign)
      } catch {
        threw = true
      }
      // The throw comes from throwIfCalledVerifier.verify() — proving verify() WAS invoked
      // even though no ElectionAttestationPolicy row exists for this electionId (A5/CR-03).
      expect(threw, 'expected associate() to throw (via the sentinel) when no policy row exists').to.be.true
    })
  })
})

// ===========================================================================
// D-14e: minimal AssociationPrivate + device-uniqueness on the non-attested path
// ===========================================================================

describe('associate() — D-14e minimal AssociationPrivate + device-uniqueness (non-attested path)', () => {
  it('AttestationRequired=0 success writes exactly one minimal AssociationPrivate row for (registrantId, deviceKey)', async () => {
    const { auth, registrantId, registrationEngine, sign, electionId } = await setupAssociationTest()
    await registrationEngine.setElectionAttestationPolicy(electionId, false, sign)

    const engine = new AssociationEngine(auth.ctx, throwIfCalledVerifier)
    const deviceKey = nextDeviceKey()
    const challenge = await engine.issueAttestationChallenge(registrantId, deviceKey, FUTURE_CHALLENGE_EXPIRATION, sign, electionId)
    // Non-attested attestation shape: deviceId populated, no cert-chain/platform material —
    // still all that's needed for the D-06 device-uniqueness check (keyed on DeviceId).
    const attestation = makeDeviceAttestation({ certificateChain: [], platformDetails: undefined })

    await engine.associate({ registrantId, deviceKey, nonce: challenge.nonce, attestation }, sign)

    const privateRow = await auth.ctx.db
      .prepare('select count(*) as n from AssociationPrivate where RegistrantId = :registrantId and DeviceKey = :deviceKey')
      .get({ registrantId, deviceKey })
    expect(Number(privateRow?.n)).to.equal(1)

    const cidRow = await auth.ctx.db
      .prepare('select AttestationCid from Association where RegistrantId = :registrantId and DeviceKey = :deviceKey')
      .get({ registrantId, deviceKey })
    expect(cidRow?.AttestationCid).to.be.a('string').with.length.greaterThan(0)
  })

  it('a second registrant reusing the SAME DeviceId on the non-attested path is REJECTED (uniqueness is path-independent)', async () => {
    const { auth, registrantId: registrantA, registrationEngine, sign, electionId } = await setupAssociationTest()
    await registrationEngine.setElectionAttestationPolicy(electionId, false, sign)

    const registrantB = nextRegistrantId()
    await registrationEngine.createRegistrant(
      { id: registrantB, authorityId: auth.authority.id, privateCid: 'assoc-policy-test-private-cid-b', expiration: FUTURE_REGISTRANT_EXPIRATION },
      sign
    )

    const engine = new AssociationEngine(auth.ctx, throwIfCalledVerifier)
    const sharedDeviceId = `assoc-policy-shared-device-${Date.now()}`

    const deviceKeyA = nextDeviceKey()
    const challengeA = await engine.issueAttestationChallenge(registrantA, deviceKeyA, FUTURE_CHALLENGE_EXPIRATION, sign, electionId)
    await engine.associate(
      { registrantId: registrantA, deviceKey: deviceKeyA, nonce: challengeA.nonce, attestation: makeDeviceAttestation({ deviceId: sharedDeviceId, certificateChain: [], platformDetails: undefined }) },
      sign
    )

    const deviceKeyB = nextDeviceKey()
    const challengeB = await engine.issueAttestationChallenge(registrantB, deviceKeyB, FUTURE_CHALLENGE_EXPIRATION, sign, electionId)
    let threw = false
    try {
      await engine.associate(
        { registrantId: registrantB, deviceKey: deviceKeyB, nonce: challengeB.nonce, attestation: makeDeviceAttestation({ deviceId: sharedDeviceId, certificateChain: [], platformDetails: undefined }) },
        sign
      )
    } catch {
      threw = true
    }
    expect(threw, 'expected the second registrant reusing the same DeviceId (no waiver) to be rejected').to.be.true

    const privateRowB = await auth.ctx.db
      .prepare('select count(*) as n from AssociationPrivate where RegistrantId = :registrantId')
      .get({ registrantId: registrantB })
    expect(Number(privateRowB?.n)).to.equal(0)
  })
})
