/**
 * ios-hardware-attestation.spec.ts — pin the iOS cross-sign verifier against REAL App Attest bytes.
 *
 * Every other iOS test in this suite runs on a synthetic Apple CA (`fixtures/attestation/
 * apple-app-attest-ca.ts`), which is the right way to stay hermetic but shares one blind spot with
 * the code it exercises: a fixture generated by the same understanding as the verifier agrees with
 * it no matter whose understanding is wrong. That is not hypothetical here — the assertion verifier
 * passed 31/31 against synthetic vectors while double-hashing the signed message, and was corrected
 * only when a real iPhone assertion refused to verify (spike 085).
 *
 * So this file's inputs come from hardware and from nowhere else: an iPhone 13 (iOS 26.x, App
 * Attest development environment) running the SHIPPING producer —
 * `createRealAttestationProducer().produce(challenge)` — on 2026-08-25. The fixture is that run's
 * verbatim output.
 *
 * The chain step (§2) is deliberately NOT asserted here. It needs Apple's real root, which this
 * repo ships empty on purpose and fails closed on (SETUP.md §4d); pinning a downloaded root inside
 * a test would quietly undo that decision. §2 is verified out-of-band by
 * `.planning/spikes/085-ios-hardware-capability-probe/verify-produce-output.ts --apple-root`.
 * What IS asserted here is the producer/verifier seam: §3's assertion over ASSERTION_DIGEST and
 * §4's proof-of-possession over POP_DIGEST, both recomputed by the verifier from the challenge
 * alone.
 */
import 'reflect-metadata'
import { expect } from 'chai'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { X509Certificate } from '@peculiar/x509'
import { cborDecode, type CborValue } from '@votetorrent/vote-core'
import { verifyCrossSign } from '../src/association/verifiers/app-attest-assertion.js'
import { recomputeChallengeDigest } from '../src/association/verifiers/digest-binding.js'

const APP_ID = '94TY7UR2W5.org.votetorrent.voter'

const fixture = JSON.parse(
  readFileSync(fileURLToPath(new URL('./fixtures/attestation/ios-hardware-2026-08-25.json', import.meta.url)), 'utf8')
) as {
  ok: boolean
  reprovisioned: boolean
  voteKeyProbe: string
  challenge: { nonce: string; deviceKey: string }
  attestation: {
    deviceId: string
    attestationStatement: string
    certificateChain: string[]
    platformDetails: {
      type: string
      secureEnclavePublicKey: string
      appAttestKeyId: string
      assertion: string
      assertionCounter: number
      popSignature: string
      boundDigest: string
      environment: string
      deviceCheckToken?: string
    }
  }
}

const b64 = (s: string): Uint8Array => new Uint8Array(Buffer.from(s, 'base64'))
const pd = fixture.attestation.platformDetails
const challenge = fixture.challenge

/** K_att's public key, read out of the credCert exactly as `verifyAppAttest` reads it on success. */
function attestedPublicKeyRaw (): Uint8Array {
  const decoded = cborDecode(b64(fixture.attestation.attestationStatement)) as Map<CborValue, CborValue>
  const attStmt = decoded.get('attStmt') as Map<CborValue, CborValue>
  const x5c = attStmt.get('x5c') as CborValue[]
  const spki = new Uint8Array(new X509Certificate(x5c[0] as Uint8Array).publicKey.rawData)
  return spki.subarray(spki.length - 65)
}

describe('iOS App Attest — REAL hardware bytes (iPhone 13, 2026-08-25)', () => {
  const appAttestPublicKeyRaw = attestedPublicKeyRaw()
  const expectations = {
    appId: APP_ID,
    challengeNonce: challenge.nonce,
    deviceKey: challenge.deviceKey,
    appAttestPublicKeyRaw
  }

  it('verifies the §3 assertion and §4 proof-of-possession produced on hardware', () => {
    const result = verifyCrossSign(b64(pd.assertion), pd.popSignature, expectations)
    // Surface the verifier's own reason on failure — a bare `false` here would cost an hour.
    expect(result.reason ?? 'ok').to.equal('ok')
    expect(result.ok).to.equal(true)
    expect(result.counter).to.equal(1)
  })

  it('agrees with the device on BOUND_DIGEST, recomputed rather than read from the submission', () => {
    expect(pd.boundDigest).to.equal(recomputeChallengeDigest(challenge.nonce, challenge.deviceKey))
  })

  it('carries a development aaguid, derived from authData and not assumed', () => {
    const decoded = cborDecode(b64(fixture.attestation.attestationStatement)) as Map<CborValue, CborValue>
    const authData = decoded.get('authData') as Uint8Array
    const aaguid = Buffer.from(authData.subarray(37, 53)).toString('latin1')
    expect(aaguid).to.equal('appattestdevelop')
    expect(pd.environment).to.equal('development')
  })

  it('binds K_vote: the submitted device key is the one the challenge was issued against', () => {
    expect(pd.secureEnclavePublicKey).to.equal(challenge.deviceKey)
    expect(fixture.attestation.deviceId).to.equal(pd.appAttestKeyId)
    expect(pd.deviceCheckToken).to.equal(undefined) // integrity bar A
  })

  // ---- negative controls ----
  //
  // Without these the suite above proves only that SOMETHING verified. Each mutation below breaks
  // exactly one binding, and each must be REJECTED — otherwise the passing case is vacuous.
  describe('negative controls', () => {
    it('rejects a tampered proof-of-possession signature', () => {
      const flipped = pd.popSignature.slice(0, -1) + (pd.popSignature.endsWith('0') ? '1' : '0')
      expect(verifyCrossSign(b64(pd.assertion), flipped, expectations).ok).to.equal(false)
    })

    it('rejects a different vote key — the assertion binds THIS K_vote', () => {
      const otherKey = '02' + 'ab'.repeat(32)
      expect(verifyCrossSign(b64(pd.assertion), pd.popSignature, { ...expectations, deviceKey: otherKey }).ok)
        .to.equal(false)
    })

    it('rejects a different challenge nonce', () => {
      expect(verifyCrossSign(b64(pd.assertion), pd.popSignature, { ...expectations, challengeNonce: 'not-the-nonce' }).ok)
        .to.equal(false)
    })

    it('rejects an assertion for a different app (rpIdHash)', () => {
      expect(verifyCrossSign(b64(pd.assertion), pd.popSignature, { ...expectations, appId: '94TY7UR2W5.org.example.other' }).ok)
        .to.equal(false)
    })

    it('rejects a replay — the counter must strictly increase', () => {
      const replay = verifyCrossSign(b64(pd.assertion), pd.popSignature, { ...expectations, previousCounter: 1 })
      expect(replay.ok).to.equal(false)
      expect(replay.reason).to.match(/replay/)
    })
  })

  // ---- the invalidated-key recovery this run also measured ----
  it('records the invalidated-key recovery that made the run possible', () => {
    // K_vote had been destroyed by a Face ID re-enrolment. Before the fix, provisionDeviceKey kept
    // returning the dead key forever and §4 could never succeed on this device.
    expect(fixture.voteKeyProbe).to.equal('CryptoTokenKit:-3')
    expect(fixture.reprovisioned).to.equal(true)
  })
})
