/**
 * ios-hardware-attestation.spec.ts — pin the iOS cross-sign verifier against REAL App Attest bytes.
 *
 * Every other iOS test in this suite runs on a synthetic Apple CA (`fixtures/attestation/
 * apple-app-attest-ca.ts`), which is the right way to stay hermetic but shares one blind spot with
 * the code it exercises: a fixture generated by the same understanding as the verifier agrees with
 * it no matter whose understanding is wrong. That is not hypothetical here — the assertion verifier
 * passed 31/31 against synthetic vectors while double-hashing the signed message, and was corrected
 * only when a real iPhone assertion refused to verify (spike 085).
 *
 * So this file's inputs come from hardware and from nowhere else: an iPhone 13 (iOS 26.x, App
 * Attest development environment) running the SHIPPING producer —
 * `createRealAttestationProducer().produce(challenge)` — on 2026-08-25. The fixture is that run's
 * verbatim output.
 *
 * §3 (the assertion over ASSERTION_DIGEST) and §4 (proof-of-possession over POP_DIGEST) are
 * asserted here, both recomputed by the verifier from the challenge alone.
 *
 * §2 — THE CHAIN — is now asserted here too, as of 2026-08-26. It previously was not, on the
 * stated grounds that it "needs Apple's real root, which this repo ships empty on purpose", and
 * that pinning a downloaded root in a test "would quietly undo that decision". The first half was
 * true and has changed: the production anchor is now provisioned and human-verified in
 * `apps/VoteTorrentAuthority/src/engines/appattest-keys.generated.ts`. The second half does not
 * apply to a fixture that `src/` cannot reach — see `fixtures/attestation/apple-app-attest-root.ts`
 * for why the src/test split is what preserved the decision, not the absence of the bytes.
 *
 * That leaves §2 the most load-bearing test in this file. It is the only assertion anywhere in the
 * repo that a chain Apple ACTUALLY ISSUED verifies under the shipped verifier and terminates at
 * Apple's ACTUAL anchor. A synthetic CA cannot prove it by construction: the fixture and the
 * verifier would simply share whichever understanding is wrong, which is exactly how the
 * double-hashed assertion survived 31 green tests.
 */
import 'reflect-metadata'
import { expect } from 'chai'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { X509Certificate } from '@peculiar/x509'
import { cborDecode, type CborValue } from '@votetorrent/vote-core'
import { verifyCrossSign } from '../src/association/verifiers/app-attest-assertion.js'
import { verifyAppAttest } from '../src/association/verifiers/app-attest.js'
import { AppAttestVerifier } from '../src/association/app-attest-verifier.js'
import { recomputeChallengeDigest } from '../src/association/verifiers/digest-binding.js'
import { APPLE_APP_ATTEST_ROOT_DER, APPLE_APP_ATTEST_ROOT_SHA256 } from './fixtures/attestation/apple-app-attest-root.js'
import { generateAppleRootCa } from './fixtures/attestation/apple-app-attest-ca.js'
import { createHash } from 'node:crypto'

const APP_ID = '94TY7UR2W5.org.votetorrent.voter'

const fixture = JSON.parse(
  readFileSync(fileURLToPath(new URL('./fixtures/attestation/ios-hardware-2026-08-25.json', import.meta.url)), 'utf8')
) as {
  startedAt: string
  ok: boolean
  reprovisioned: boolean
  voteKeyProbe: string
  challenge: { nonce: string; deviceKey: string }
  attestation: {
    deviceId: string
    attestationStatement: string
    certificateChain: string[]
    platformDetails: {
      type: string
      secureEnclavePublicKey: string
      appAttestKeyId: string
      assertion: string
      assertionCounter: number
      popSignature: string
      boundDigest: string
      environment: string
      deviceCheckToken?: string
    }
  }
}

const b64 = (s: string): Uint8Array => new Uint8Array(Buffer.from(s, 'base64'))
const pd = fixture.attestation.platformDetails
const challenge = fixture.challenge

/**
 * The real device's own capture timestamp, read from the fixture rather than hardcoded. Apple App
 * Attest development-environment leaf certs are short-lived (this chain's credCert is valid for
 * only 3 days), so a fixed real-hardware fixture inevitably crosses its own validity window as
 * wall-clock time passes. Verifying at CAPTURE time — not `new Date()` — lets this spec keep
 * proving chain structure and signatures against genuine Apple bytes without decaying. Nothing in
 * the shipped verifier ever passes an injected `now`; see `app-attest.ts`'s `now?: Date` doc.
 */
const FIXTURE_CAPTURED_AT = new Date(fixture.startedAt)

/** K_att's public key, read out of the credCert exactly as `verifyAppAttest` reads it on success. */
function attestedPublicKeyRaw (): Uint8Array {
  const decoded = cborDecode(b64(fixture.attestation.attestationStatement)) as Map<CborValue, CborValue>
  const attStmt = decoded.get('attStmt') as Map<CborValue, CborValue>
  const x5c = attStmt.get('x5c') as CborValue[]
  const spki = new Uint8Array(new X509Certificate(x5c[0] as Uint8Array).publicKey.rawData)
  return spki.subarray(spki.length - 65)
}

describe('iOS App Attest — REAL hardware bytes (iPhone 13, 2026-08-25)', () => {
  const appAttestPublicKeyRaw = attestedPublicKeyRaw()
  const expectations = {
    appId: APP_ID,
    challengeNonce: challenge.nonce,
    deviceKey: challenge.deviceKey,
    appAttestPublicKeyRaw
  }

  it('verifies the §3 assertion and §4 proof-of-possession produced on hardware', () => {
    const result = verifyCrossSign(b64(pd.assertion), pd.popSignature, expectations)
    // Surface the verifier's own reason on failure — a bare `false` here would cost an hour.
    expect(result.reason ?? 'ok').to.equal('ok')
    expect(result.ok).to.equal(true)
    expect(result.counter).to.equal(1)
  })

  it('agrees with the device on BOUND_DIGEST, recomputed rather than read from the submission', () => {
    expect(pd.boundDigest).to.equal(recomputeChallengeDigest(challenge.nonce, challenge.deviceKey))
  })

  it('carries a development aaguid, derived from authData and not assumed', () => {
    const decoded = cborDecode(b64(fixture.attestation.attestationStatement)) as Map<CborValue, CborValue>
    const authData = decoded.get('authData') as Uint8Array
    const aaguid = Buffer.from(authData.subarray(37, 53)).toString('latin1')
    expect(aaguid).to.equal('appattestdevelop')
    expect(pd.environment).to.equal('development')
  })

  it('binds K_vote: the submitted device key is the one the challenge was issued against', () => {
    expect(pd.secureEnclavePublicKey).to.equal(challenge.deviceKey)
    expect(fixture.attestation.deviceId).to.equal(pd.appAttestKeyId)
    expect(pd.deviceCheckToken).to.equal(undefined) // integrity bar A
  })

  // ---- negative controls ----
  //
  // Without these the suite above proves only that SOMETHING verified. Each mutation below breaks
  // exactly one binding, and each must be REJECTED — otherwise the passing case is vacuous.
  describe('negative controls', () => {
    it('rejects a tampered proof-of-possession signature', () => {
      const flipped = pd.popSignature.slice(0, -1) + (pd.popSignature.endsWith('0') ? '1' : '0')
      expect(verifyCrossSign(b64(pd.assertion), flipped, expectations).ok).to.equal(false)
    })

    it('rejects a different vote key — the assertion binds THIS K_vote', () => {
      const otherKey = '02' + 'ab'.repeat(32)
      expect(verifyCrossSign(b64(pd.assertion), pd.popSignature, { ...expectations, deviceKey: otherKey }).ok)
        .to.equal(false)
    })

    it('rejects a different challenge nonce', () => {
      expect(verifyCrossSign(b64(pd.assertion), pd.popSignature, { ...expectations, challengeNonce: 'not-the-nonce' }).ok)
        .to.equal(false)
    })

    it('rejects an assertion for a different app (rpIdHash)', () => {
      expect(verifyCrossSign(b64(pd.assertion), pd.popSignature, { ...expectations, appId: '94TY7UR2W5.org.example.other' }).ok)
        .to.equal(false)
    })

    it('rejects a replay — the counter must strictly increase', () => {
      const replay = verifyCrossSign(b64(pd.assertion), pd.popSignature, { ...expectations, previousCounter: 1 })
      expect(replay.ok).to.equal(false)
      expect(replay.reason).to.match(/replay/)
    })
  })

  // ---- §2: the chain, against Apple's REAL anchor (added 2026-08-26) ----
  describe('\u00a72 chain \u2014 real Apple bytes against the real Apple root', () => {
    const boundDigest = recomputeChallengeDigest(challenge.nonce, challenge.deviceKey)
    const expectedClientDataHash = new Uint8Array(
      createHash('sha256').update(new TextEncoder().encode(boundDigest)).digest()
    )
    const keyId = b64(pd.appAttestKeyId)
    const attObj = b64(fixture.attestation.attestationStatement)

    it('the fixture root is the anchor the app pins (same fingerprint literal)', () => {
      // Cross-file drift guard. The production anchor lives in the authority app and cannot be
      // imported from here; the shared literal is what links them. Refreshing one without the
      // other breaks this pair rather than silently testing a root nobody ships.
      const actual = createHash('sha256').update(APPLE_APP_ATTEST_ROOT_DER).digest('hex')
      expect(actual).to.equal(APPLE_APP_ATTEST_ROOT_SHA256)
      expect(APPLE_APP_ATTEST_ROOT_SHA256)
        .to.equal('1cb9823ba28ba6ad2d33a006941de2ae4f513ef1d4e831b9f7e0fa7b6242c932')
    })

    it('verifies a chain Apple actually issued, terminating at Apple\u2019s actual root', async () => {
      const r = await verifyAppAttest(attObj, {
        appId: APP_ID,
        expectedClientDataHash,
        keyId,
        pinnedRootsDer: [APPLE_APP_ATTEST_ROOT_DER],
        environment: 'development',
        now: FIXTURE_CAPTURED_AT
      })
      expect(r.reason ?? '').to.equal('')
      expect(r.ok).to.equal(true)
    })

    it('NEGATIVE CONTROL: still rejects this same real chain when "now" is genuinely outside its validity window', async () => {
      // Proves the capture-time seam did not quietly disable expiry checking. Without this, a
      // seam that can no longer fail would be worse than the freshness problem it fixes.
      const farFuture = new Date('2030-01-01T00:00:00.000Z')
      const r = await verifyAppAttest(attObj, {
        appId: APP_ID,
        expectedClientDataHash,
        keyId,
        pinnedRootsDer: [APPLE_APP_ATTEST_ROOT_DER],
        environment: 'development',
        now: farFuture
      })
      expect(r.ok).to.equal(false)
      expect(r.reason).to.match(/expired or not yet valid/)
    })

    it('rejects the same real attestation under a DIFFERENT anchor', async () => {
      // The negative control that gives the test above its meaning. Without it, a verifier that
      // ignored the pinned pool entirely would pass identically. The chain here is Apple's real
      // one \u2014 only the anchor is wrong \u2014 so this isolates the pinned-terminus check,
      // which spike 081 identified as the ONLY guard against a self-supplied trust anchor.
      //
      // The anchor is a well-formed CA that simply is not Apple's, which is the actual attack
      // shape. An earlier version of this test instead flipped one byte of the REAL root and
      // pinned that, and it passed-as-accepted \u2014 correctly. `X509ChainBuilder` matches an
      // issuer by name and KEY, and the terminus check then compares the built terminus against
      // the pinned pool, so supplying a mutated root and pinning that same mutated root is
      // self-consistent by construction. It also tells you something worth keeping: a root's own
      // self-signature is not load-bearing \u2014 the trust sits in its public key.
      const otherCa = await generateAppleRootCa('CN=Not Apple App Attest Root CA')
      const r = await verifyAppAttest(attObj, {
        appId: APP_ID,
        expectedClientDataHash,
        keyId,
        pinnedRootsDer: [new Uint8Array(otherCa.cert.rawData)],
        environment: 'development'
      })
      expect(r.ok).to.equal(false)
    })

    it('rejects a real attestation against an EMPTY pinned pool (fail closed, not fail open)', async () => {
      const r = await verifyAppAttest(attObj, {
        appId: APP_ID,
        expectedClientDataHash,
        keyId,
        pinnedRootsDer: [],
        environment: 'development'
      })
      expect(r.ok).to.equal(false)
    })
  })

  // ---- the composed verifier, end to end, on real bytes ----
  describe('AppAttestVerifier \u2014 both halves over one real device submission', () => {
    it('accepts the real hardware attestation with the real root pinned', async () => {
      // The whole point of the phase, in one assertion: attestation + cross-sign + POP, composed as
      // the app composes them, over bytes an iPhone produced, anchored to Apple. Everything else in
      // this suite tests a piece.
      const verifier = new AppAttestVerifier(
        [APPLE_APP_ATTEST_ROOT_DER], APP_ID, 'development', undefined, true, FIXTURE_CAPTURED_AT
      )
      const r = await verifier.verify(challenge, fixture.attestation)
      expect(r.reason ?? '').to.equal('')
      expect(r.ok).to.equal(true)
    })

    it('NEGATIVE CONTROL: the composed verifier still rejects when "now" is genuinely outside the chain’s validity window', async () => {
      const verifier = new AppAttestVerifier(
        [APPLE_APP_ATTEST_ROOT_DER], APP_ID, 'development', undefined, true, new Date('2030-01-01T00:00:00.000Z')
      )
      const r = await verifier.verify(challenge, fixture.attestation)
      expect(r.ok).to.equal(false)
      expect(r.reason).to.match(/expired or not yet valid/)
    })

    it('a PRODUCTION authority refuses this development attestation', async () => {
      // The asymmetry that matters for shipping: these exact bytes, which are valid, must NOT be
      // accepted by a production authority. The credCert aaguid is the only thing separating them.
      const verifier = new AppAttestVerifier([APPLE_APP_ATTEST_ROOT_DER], APP_ID, 'production')
      const r = await verifier.verify(challenge, fixture.attestation)
      expect(r.ok).to.equal(false)
      expect(r.reason).to.match(/development attestation is never accepted in production/)
    })

    it('reports the unprovisioned root FIRST, even on otherwise-valid real bytes', async () => {
      // The state the authority app ships in today for the App ID half. A valid submission must
      // still be refused, and the reason must name the configuration rather than the device.
      const verifier = new AppAttestVerifier([], APP_ID, 'development')
      const r = await verifier.verify(challenge, fixture.attestation)
      expect(r.ok).to.equal(false)
      expect(r.reason).to.match(/root material is not provisioned/)
    })
  })

  // ---- the invalidated-key recovery this run also measured ----
  it('records the invalidated-key recovery that made the run possible', () => {
    // K_vote had been destroyed by a Face ID re-enrolment. Before the fix, provisionDeviceKey kept
    // returning the dead key forever and §4 could never succeed on this device.
    expect(fixture.voteKeyProbe).to.equal('CryptoTokenKit:-3')
    expect(fixture.reprovisioned).to.equal(true)
  })
})
