/**
 * ios-producer-verifier-agreement.spec.ts
 *
 * The iOS ceremony has TWO independent implementations of the same two digests:
 *   - the DEVICE producer   — packages/attestation-native/src/real-attestation-producer.ts
 *   - the AUTHORITY verifier — src/association/verifiers/app-attest-assertion.ts
 *
 * They are deliberately separate: the authority engine must not take a dependency on the
 * device-side module (that drags React Native into its graph — measured, it breaks `yarn install`
 * peer resolution). The price of that independence is DRIFT — a changed domain tag, a reordered
 * field, a different output encoding. Drift never fails loudly; it fails as "signature invalid" on
 * every real iOS association.
 *
 * WHY LITERALS, AND WHERE THEY CAME FROM: the expected values below are CAPTURED OUTPUT of the
 * PRODUCER implementation (run directly via `node --experimental-strip-types` against
 * real-attestation-producer.ts, 2026-08-25). They are NOT recomputed from the verifier under test.
 * That distinction is the whole point — a fixture generated by the code it checks agrees with it by
 * construction, which is exactly how a double-hashed assertion verifier passed 31/31 until real
 * hardware refuted it (ATTESTATION-CONTRACT-IOS.md §3.3). If either side drifts, these fail.
 *
 * To regenerate after an INTENTIONAL contract change, re-run the producer and update both it and
 * ATTESTATION-CONTRACT-IOS.md — never edit these to match a surprising verifier result.
 */
import { expect } from 'aegir/chai'
import { computeAssertionDigest, computePopDigest } from '../src/association/verifiers/app-attest-assertion.js'

const BOUND_DIGEST = 'Zm9vYmFyLWJvdW5kLWRpZ2VzdC12MQ'
const VOTE_KEY = '037466ee648ca4fbfdb0c73d9cc4793f23731b12ab7d4e2f9c1a5b6d8e0f2a4c61'

// Captured from the device-side producer — see header.
const PRODUCER_ASSERTION_DIGEST = 'qj0NDLLaVe4V6OiVpXAmjpWUYBGl9gjSbnL4bTAvlq0'
const PRODUCER_POP_DIGEST = 'r5qWYwwxVl0tNqJVg4jiH5cG_EtRiqDdIogMhCZydjg'

describe('iOS producer/verifier digest agreement', () => {
  it('ASSERTION_DIGEST matches the device producer byte-for-byte (§3.1)', () => {
    expect(computeAssertionDigest(BOUND_DIGEST, VOTE_KEY)).to.equal(PRODUCER_ASSERTION_DIGEST)
  })

  it('POP_DIGEST matches the device producer byte-for-byte (§4)', () => {
    expect(computePopDigest(BOUND_DIGEST)).to.equal(PRODUCER_POP_DIGEST)
  })

  it('the two digests are domain-separated (a possession signature must not replay as a cross-sign)', () => {
    // Both commit to BOUND_DIGEST; only the tag (and arity) separates them.
    expect(computeAssertionDigest(BOUND_DIGEST, VOTE_KEY)).to.not.equal(computePopDigest(BOUND_DIGEST))
  })

  it('ASSERTION_DIGEST commits to K_vote — a different vote key yields a different digest', () => {
    const other = '02' + VOTE_KEY.slice(2)
    expect(computeAssertionDigest(BOUND_DIGEST, VOTE_KEY)).to.not.equal(computeAssertionDigest(BOUND_DIGEST, other))
  })

  it('ASSERTION_DIGEST is field-ORDER sensitive (guards against non-injective concatenation)', () => {
    // digestFields is length-prefixed and type-tagged precisely so swapped fields cannot collide.
    // If this ever passes, someone has replaced it with string concatenation.
    expect(computeAssertionDigest(BOUND_DIGEST, VOTE_KEY)).to.not.equal(computeAssertionDigest(VOTE_KEY, BOUND_DIGEST))
  })
})
