/**
 * sealed-payload.spec.ts — Phase 52 Plan 01 (D-04, D-05)
 *
 * Proves the two cryptographic primitives every other plan in this phase
 * builds on:
 *
 *   D-04 — the domain-separated key split. `lookupId` (the half the
 *          rendezvous service sees) and `contentKey` (the half it must
 *          never see) are two different HMAC-SHA256 derivations of one
 *          20-byte secret. The split is FORCED, not preferred: `redeem()`
 *          is called with the secret itself, so keying the cipher on the
 *          raw secret would hand the service the decryption key alongside
 *          the ciphertext.
 *
 *   D-05 — the AES-256-GCM seal/unseal wrapper over the
 *          `{ v, nonce, ciphertext }` base64url shape.
 *
 * Two DIFFERENT kinds of vector live in this file and must not be
 * conflated:
 *
 *   a) INDEPENDENT-IMPLEMENTATION KATs (KAT-1/2/3). Computed here from
 *      `node:crypto` (OpenSSL) and compared against `@noble/*`. These are
 *      genuine cross-implementation checks — a bug shared by both
 *      implementations is the only way they pass wrongly. `node:crypto` is
 *      a TEST-TIER tool only; importing it from `src/bootstrap/` is
 *      forbidden and G-3 enforces that.
 *
 *   b) FROZEN REGRESSION PINS (`FROZEN_*`). Generated by this repo, not by
 *      an independent authority. They prove nothing about correctness; they
 *      exist so a later refactor that swaps the HMAC argument order,
 *      renames a label, or changes the encoding fails loudly. They are also
 *      the cross-runtime parity vectors 52-05 (browser) and 52-07 (Hermes)
 *      re-run byte-for-byte.
 *
 * DECLARED BLIND SPOT: this spec proves the primitives' ARITHMETIC on the
 * host running mocha. It says nothing about whether Metro/Hermes can bundle
 * `@noble/ciphers` at all, nor whether `crypto.getRandomValues` is present
 * on a real device — that proof is 52-07's device gate. It also exercises
 * no transport, no service and no IndexedDB.
 */

import { expect } from 'chai'
import { createCipheriv, createHmac } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  BOOTSTRAP_CONTENT_LABEL,
  BOOTSTRAP_LOOKUP_LABEL,
  BOOTSTRAP_SECRET_MIN_BYTES,
  SEALED_PAYLOAD_FORMAT_VERSION,
  SEALED_PAYLOAD_KEY_BYTES,
  SEALED_PAYLOAD_NONCE_BYTES,
  deriveBootstrapKeys,
  sealPayload,
  sealPayloadWithNonce,
  unsealPayload
} from '../src/bootstrap/sealed-payload.js'
import type { BootstrapKeySplit, SealedPayload } from '../src/bootstrap/sealed-payload.js'

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

/**
 * The frozen 20-byte secret: bytes 0x00..0x13. Deliberately a trivially
 * re-typeable pattern so 52-05 (browser) and 52-07 (Hermes) can reconstruct
 * it without importing anything from this package. NOT a real secret and
 * never produced by `mintDashboardSignInCode`, which draws 20 bytes from
 * `crypto.getRandomValues`.
 */
const FROZEN_SECRET = Uint8Array.from({ length: 20 }, (_, i) => i)

/** The frozen 12-byte nonce: bytes 0xa0..0xab. TEST USE ONLY. */
const FROZEN_NONCE = Uint8Array.from({ length: 12 }, (_, i) => 0xa0 + i)

/** The frozen plaintext. ASCII only, so byte-for-byte re-typeable anywhere. */
const FROZEN_PLAINTEXT = '{"formatVersion":1,"note":"sealed-payload KAT"}'

/**
 * FROZEN REGRESSION PIN (repo-generated, 2026-08-29) — the `lookupId` for
 * `FROZEN_SECRET`. 43 unpadded base64url characters.
 */
const FROZEN_LOOKUP_ID = 'ChcvGsUJw1ir4PjcOFo4R7GL4JOfMN6Hx8XeiYndv-g'

/**
 * FROZEN REGRESSION PIN (repo-generated, 2026-08-29) — `JSON.stringify` of
 * `sealPayloadWithNonce(FROZEN_PLAINTEXT, deriveBootstrapKeys(FROZEN_SECRET), FROZEN_NONCE)`.
 * Member order is `v`, `nonce`, `ciphertext` — the construction order in
 * `sealed-payload.ts`. 52-05 and 52-07 re-run this exact string.
 */
const FROZEN_WRAPPER_JSON =
  '{"v":1,"nonce":"oKGio6Slpqeoqaqr","ciphertext":"qaNuu-SiY3SKnTPPJxUvEXKRXKAhE5zlJ7X6ZDqobSP_1Q41vhd8oqEevF2smN4vqNKyVgJaeUQ231YlXF_Q"}'

/** A second, distinct 20-byte secret, for the divergence + negative controls. */
const OTHER_SECRET = Uint8Array.from({ length: 20 }, (_, i) => 0xff - i)

/**
 * The canary marker. Borrowed from `snapshot-manifest.spec.ts:45`. Any
 * `detail` string, or any serialized wrapper, that contains it has leaked
 * plaintext.
 */
const PII_CANARY = 'PII-CANARY-9f3a'

/** A payload with multi-byte UTF-8 and the canary. */
const CANARY_PLAINTEXT = `{"registrant":"Ana Muñoz — 日本語 🗳","marker":"${PII_CANARY}"}`

const toBase64url = (bytes: Uint8Array): string => Buffer.from(bytes).toString('base64url')
const fromBase64url = (s: string): Uint8Array => new Uint8Array(Buffer.from(s, 'base64url'))

/** Independent (OpenSSL) reference for one label. Label is HMAC's KEY slot. */
function nodeHmac (label: string, secret: Uint8Array): Buffer {
  return createHmac('sha256', Buffer.from(label, 'utf8')).update(secret).digest()
}

/** Independent (OpenSSL) reference for the whole cipher step, tag appended. */
function nodeSeal (contentKey: Uint8Array, nonce: Uint8Array, lookupId: string, plaintext: string): Buffer {
  const cipher = createCipheriv('aes-256-gcm', contentKey, nonce)
  cipher.setAAD(Buffer.from(lookupId, 'utf8'))
  const body = Buffer.concat([cipher.update(Buffer.from(plaintext, 'utf8')), cipher.final()])
  return Buffer.concat([body, cipher.getAuthTag()])
}

describe('bootstrap sealed payload (52-01, D-04/D-05)', () => {
  // -------------------------------------------------------------------------
  // KAT-1 — the KDF, against node:crypto
  // -------------------------------------------------------------------------
  describe('KAT-1 — deriveBootstrapKeys vs node:crypto HMAC-SHA256', () => {
    it('KAT-1a: contentKey is byte-identical to OpenSSL HMAC-SHA256(key=bootstrap-content, msg=secret)', () => {
      const { contentKey } = deriveBootstrapKeys(FROZEN_SECRET)
      const reference = nodeHmac('bootstrap-content', FROZEN_SECRET)
      expect(Buffer.from(contentKey).equals(reference), 'noble HMAC must agree with OpenSSL for the content label').to.equal(true)
      expect(contentKey.length, 'contentKey must be exactly SEALED_PAYLOAD_KEY_BYTES').to.equal(SEALED_PAYLOAD_KEY_BYTES)
      expect(contentKey, 'contentKey must be raw bytes, never a string').to.be.instanceOf(Uint8Array)
    })

    it('KAT-1b: lookupId is base64url of OpenSSL HMAC-SHA256(key=bootstrap-lookup, msg=secret)', () => {
      const { lookupId } = deriveBootstrapKeys(FROZEN_SECRET)
      const reference = nodeHmac('bootstrap-lookup', FROZEN_SECRET).toString('base64url')
      expect(lookupId, 'noble HMAC + base64url must agree with OpenSSL for the lookup label').to.equal(reference)
    })

    it('KAT-1c: the labels are exactly the two locked strings (argument order is label-as-key)', () => {
      expect(BOOTSTRAP_LOOKUP_LABEL, 'lookup label is locked by 52-01').to.equal('bootstrap-lookup')
      expect(BOOTSTRAP_CONTENT_LABEL, 'content label is locked by 52-01').to.equal('bootstrap-content')
      // Swapping HMAC's key/message slots would still produce 32 bytes, so
      // this is checked by KAT-1a/1b's byte equality, not by a length test.
      const swapped = createHmac('sha256', Buffer.from(FROZEN_SECRET)).update(Buffer.from('bootstrap-content', 'utf8')).digest()
      const { contentKey } = deriveBootstrapKeys(FROZEN_SECRET)
      expect(Buffer.from(contentKey).equals(swapped), 'the secret must be the MESSAGE, not the KEY — swapped order must NOT match').to.equal(false)
    })
  })

  // -------------------------------------------------------------------------
  // KAT-2 — the cipher, against node:crypto
  // -------------------------------------------------------------------------
  describe('KAT-2 — sealPayloadWithNonce vs node:crypto AES-256-GCM', () => {
    it('KAT-2a: ciphertext is byte-identical to OpenSSL aes-256-gcm with lookupId as AAD', () => {
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      const sealed = sealPayloadWithNonce(FROZEN_PLAINTEXT, keys, FROZEN_NONCE)
      const reference = nodeSeal(keys.contentKey, FROZEN_NONCE, keys.lookupId, FROZEN_PLAINTEXT)
      expect(fromBase64url(sealed.ciphertext), 'noble gcm() must be standard AES-256-GCM').to.deep.equal(new Uint8Array(reference))
    })

    it('KAT-2b: the 16-byte tag is APPENDED, not prepended', () => {
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      const sealed = sealPayloadWithNonce(FROZEN_PLAINTEXT, keys, FROZEN_NONCE)
      const bytes = fromBase64url(sealed.ciphertext)
      const cipher = createCipheriv('aes-256-gcm', keys.contentKey, FROZEN_NONCE)
      cipher.setAAD(Buffer.from(keys.lookupId, 'utf8'))
      const body = Buffer.concat([cipher.update(Buffer.from(FROZEN_PLAINTEXT, 'utf8')), cipher.final()])
      const tag = cipher.getAuthTag()

      expect(bytes.length, 'ciphertext length must be body + a 16-byte tag').to.equal(body.length + 16)
      expect(Buffer.from(bytes.slice(0, body.length)).equals(body), 'the first bytes must be the message body').to.equal(true)
      expect(Buffer.from(bytes.slice(bytes.length - 16)).equals(tag), 'the LAST 16 bytes must be the auth tag').to.equal(true)
    })

    it('KAT-2c: the nonce carried in the wrapper is the nonce that was used', () => {
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      const sealed = sealPayloadWithNonce(FROZEN_PLAINTEXT, keys, FROZEN_NONCE)
      expect(fromBase64url(sealed.nonce), 'wrapper nonce must round-trip to the supplied bytes').to.deep.equal(FROZEN_NONCE)
    })
  })

  // -------------------------------------------------------------------------
  // KAT-3 — the hand-rolled base64url encoder, against Node's native one
  // -------------------------------------------------------------------------
  describe('KAT-3 — hand-rolled btoa/atob base64url vs Node native base64url', () => {
    it('KAT-3a: every string the module emits decodes through Node base64url and re-encodes identically', () => {
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      const sealed = sealPayloadWithNonce(FROZEN_PLAINTEXT, keys, FROZEN_NONCE)
      for (const [name, s] of [['lookupId', keys.lookupId], ['nonce', sealed.nonce], ['ciphertext', sealed.ciphertext]] as const) {
        const bytes = fromBase64url(s)
        expect(toBase64url(bytes), `${name} must agree with Node's native base64url encoder`).to.equal(s)
      }
    })

    it('KAT-3b: emitted strings are UNPADDED and use the URL alphabet only', () => {
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      const sealed = sealPayloadWithNonce(FROZEN_PLAINTEXT, keys, FROZEN_NONCE)
      for (const [name, s] of [['lookupId', keys.lookupId], ['nonce', sealed.nonce], ['ciphertext', sealed.ciphertext]] as const) {
        expect(s, `${name} must not carry '=' padding`).to.not.match(/=/)
        expect(s, `${name} must not carry the standard-base64 '+' or '/'`).to.not.match(/[+/]/)
        expect(s, `${name} must be base64url alphabet only`).to.match(/^[A-Za-z0-9_-]+$/)
      }
    })

    it('KAT-3c: the encoder agrees with Node for every remainder-mod-3 length (0, 1, 2)', () => {
      // Lengths 30/31/32 cover all three base64 padding cases. Exercised via
      // real emitted strings by sealing three plaintexts of differing length.
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      for (const len of [30, 31, 32]) {
        const sealed = sealPayloadWithNonce('x'.repeat(len), keys, FROZEN_NONCE)
        const bytes = fromBase64url(sealed.ciphertext)
        expect(bytes.length, `plaintext of ${len} bytes must yield ${len} + 16 ciphertext bytes`).to.equal(len + 16)
        expect(toBase64url(bytes), `encoder must agree with Node at plaintext length ${len}`).to.equal(sealed.ciphertext)
      }
    })
  })

  // -------------------------------------------------------------------------
  // Frozen regression pins (repo-generated — NOT independent vectors)
  // -------------------------------------------------------------------------
  describe('frozen regression pins (repo-generated; re-run byte-for-byte by 52-05 and 52-07)', () => {
    it('PIN-1: deriveBootstrapKeys(FROZEN_SECRET).lookupId equals the checked-in literal', () => {
      expect(deriveBootstrapKeys(FROZEN_SECRET).lookupId, 'a change here means the label, the HMAC argument order or the encoding moved').to.equal(FROZEN_LOOKUP_ID)
    })

    it('PIN-2: the whole {v,nonce,ciphertext} wrapper JSON equals the checked-in literal', () => {
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      const sealed = sealPayloadWithNonce(FROZEN_PLAINTEXT, keys, FROZEN_NONCE)
      expect(JSON.stringify(sealed), 'wrapper JSON (including member order) is a cross-runtime parity vector').to.equal(FROZEN_WRAPPER_JSON)
    })

    it('PIN-3: the frozen wrapper unseals back to the frozen plaintext', () => {
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      const result = unsealPayload(JSON.parse(FROZEN_WRAPPER_JSON), keys)
      expect(result.ok, 'the frozen pin must be decryptable, or the pin itself is wrong').to.equal(true)
      if (result.ok) expect(result.plaintext).to.equal(FROZEN_PLAINTEXT)
    })
  })

  // -------------------------------------------------------------------------
  // Round trip
  // -------------------------------------------------------------------------
  describe('seal/unseal round trip', () => {
    it('RT-1: an ASCII payload round-trips to the exact original string', () => {
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      const result = unsealPayload(sealPayload(FROZEN_PLAINTEXT, keys), keys)
      expect(result.ok, 'round trip must succeed').to.equal(true)
      if (result.ok) expect(result.plaintext, 'plaintext must be strictly equal to the original').to.equal(FROZEN_PLAINTEXT)
    })

    it('RT-2: a multi-byte UTF-8 payload carrying the PII canary round-trips exactly', () => {
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      const result = unsealPayload(sealPayload(CANARY_PLAINTEXT, keys), keys)
      expect(result.ok, 'round trip must succeed for multi-byte UTF-8').to.equal(true)
      if (result.ok) expect(result.plaintext, 'multi-byte UTF-8 must survive byte-for-byte').to.equal(CANARY_PLAINTEXT)
    })

    it('RT-3: an empty payload round-trips to the empty string', () => {
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      const result = unsealPayload(sealPayload('', keys), keys)
      expect(result.ok, 'an empty plaintext is still a valid payload').to.equal(true)
      if (result.ok) expect(result.plaintext).to.equal('')
    })

    it('RT-4: the wrapper carries the locked literal format version', () => {
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      expect(sealPayload(FROZEN_PLAINTEXT, keys).v, 'v must be SEALED_PAYLOAD_FORMAT_VERSION').to.equal(SEALED_PAYLOAD_FORMAT_VERSION)
      expect(SEALED_PAYLOAD_FORMAT_VERSION, 'the literal for this phase is 1').to.equal(1)
    })
  })

  // -------------------------------------------------------------------------
  // Nonce freshness (T-52-01-05)
  // -------------------------------------------------------------------------
  describe('nonce freshness', () => {
    it('NF-1: two sealPayload calls with identical arguments produce different nonces AND different ciphertexts', () => {
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      const a = sealPayload(FROZEN_PLAINTEXT, keys)
      const b = sealPayload(FROZEN_PLAINTEXT, keys)
      expect(a.nonce, 'a repeated nonce under one AES-GCM key is catastrophic').to.not.equal(b.nonce)
      expect(a.ciphertext, 'a fresh nonce must change the ciphertext').to.not.equal(b.ciphertext)
    })

    it('NF-2: the generated nonce decodes to exactly SEALED_PAYLOAD_NONCE_BYTES bytes', () => {
      const keys = deriveBootstrapKeys(FROZEN_SECRET)
      for (let i = 0; i < 8; i++) {
        const sealed = sealPayload(FROZEN_PLAINTEXT, keys)
        expect(fromBase64url(sealed.nonce).length, 'GCM nonce must be 12 bytes').to.equal(SEALED_PAYLOAD_NONCE_BYTES)
      }
      expect(SEALED_PAYLOAD_NONCE_BYTES, 'the locked GCM nonce length is 12').to.equal(12)
    })
  })

  // -------------------------------------------------------------------------
  // D-04 domain separation
  // -------------------------------------------------------------------------
  describe('D-04 domain separation', () => {
    it('DS-1: lookupId decoded to bytes is NOT equal to contentKey for the same secret', () => {
      const { lookupId, contentKey } = deriveBootstrapKeys(FROZEN_SECRET)
      expect(Buffer.from(fromBase64url(lookupId)).equals(Buffer.from(contentKey)), 'both halves derived from ONE label is the copy-paste bug this catches').to.equal(false)
    })

    it('DS-2: the two labels are different strings', () => {
      expect(BOOTSTRAP_LOOKUP_LABEL, 'domain separation requires two distinct labels').to.not.equal(BOOTSTRAP_CONTENT_LABEL)
    })

    it('DS-3: two distinct secrets produce distinct lookupIds AND distinct contentKeys', () => {
      const a = deriveBootstrapKeys(FROZEN_SECRET)
      const b = deriveBootstrapKeys(OTHER_SECRET)
      expect(a.lookupId, 'a different secret must yield a different lookupId').to.not.equal(b.lookupId)
      expect(Buffer.from(a.contentKey).equals(Buffer.from(b.contentKey)), 'a different secret must yield a different contentKey').to.equal(false)
    })

    it('DS-4: derivation is deterministic — the same secret always yields the same split', () => {
      const a = deriveBootstrapKeys(FROZEN_SECRET)
      const b = deriveBootstrapKeys(Uint8Array.from(FROZEN_SECRET))
      expect(a.lookupId, 'the KDF must be a pure function of the secret').to.equal(b.lookupId)
      expect(Buffer.from(a.contentKey).equals(Buffer.from(b.contentKey)), 'the KDF must be a pure function of the secret').to.equal(true)
    })
  })

  // -------------------------------------------------------------------------
  // Downstream path-segment contract (52-03 depends on this)
  // -------------------------------------------------------------------------
  describe('lookupId path-segment contract (filesystem-bootstrap-transport.ts:43)', () => {
    it('PS-1: every produced lookupId matches /^[A-Za-z0-9_-]{43}$/ over 200 random secrets', () => {
      for (let i = 0; i < 200; i++) {
        const secret = new Uint8Array(20)
        for (let j = 0; j < secret.length; j++) secret[j] = (i * 31 + j * 17) & 0xff
        const { lookupId } = deriveBootstrapKeys(secret)
        expect(lookupId, `lookupId #${i} must be 43 path-safe base64url characters`).to.match(/^[A-Za-z0-9_-]{43}$/)
      }
    })

    it('PS-2: a lookupId can never be \'.\', \'..\' or contain a \'..\' traversal segment', () => {
      // The alphabet excludes '.' entirely, so this is structural, not statistical.
      for (let i = 0; i < 50; i++) {
        const secret = new Uint8Array(20)
        for (let j = 0; j < secret.length; j++) secret[j] = (i * 7 + j * 3) & 0xff
        const { lookupId } = deriveBootstrapKeys(secret)
        expect(lookupId.includes('.'), 'the base64url alphabet contains no dot, so no traversal segment is representable').to.equal(false)
      }
    })

    it('PS-3: the produced lookupId satisfies SAFE_IDENTIFIER_PATTERN /^[A-Za-z0-9_.-]{1,128}$/', () => {
      const { lookupId } = deriveBootstrapKeys(FROZEN_SECRET)
      expect(lookupId, '52-03 uses lookupId as a filesystem path segment').to.match(/^[A-Za-z0-9_.-]{1,128}$/)
    })
  })

  // -------------------------------------------------------------------------
  // Secret-length guard (T-52-01-07)
  // -------------------------------------------------------------------------
  describe('deriveBootstrapKeys secret guard', () => {
    it('SG-1: a 20-byte Uint8Array secret is accepted (paired positive control)', () => {
      expect(() => deriveBootstrapKeys(FROZEN_SECRET), 'the real 20-byte mint output must be accepted').to.not.throw()
    })

    it('SG-2: a non-Uint8Array input throws, naming the constraint', () => {
      expect(() => deriveBootstrapKeys('0001020304' as unknown as Uint8Array)).to.throw(/Uint8Array/)
      expect(() => deriveBootstrapKeys(null as unknown as Uint8Array)).to.throw(/Uint8Array/)
      expect(() => deriveBootstrapKeys([1, 2, 3] as unknown as Uint8Array)).to.throw(/Uint8Array/)
    })

    it('SG-3: a secret shorter than BOOTSTRAP_SECRET_MIN_BYTES throws, naming the constraint', () => {
      expect(() => deriveBootstrapKeys(new Uint8Array(15)), 'a 15-byte secret is below the floor').to.throw(/at least 16 bytes/)
      expect(() => deriveBootstrapKeys(new Uint8Array(0)), 'an empty secret is below the floor').to.throw(/at least 16 bytes/)
      expect(BOOTSTRAP_SECRET_MIN_BYTES, 'the locked floor is 16 bytes').to.equal(16)
      expect(() => deriveBootstrapKeys(new Uint8Array(16)), 'exactly the floor is accepted (boundary positive control)').to.not.throw()
    })

    it('SG-4: the guard message carries the observed LENGTH only, never the secret bytes', () => {
      const secret = new Uint8Array([0xde, 0xad, 0xbe, 0xef])
      let message = ''
      try {
        deriveBootstrapKeys(secret)
      } catch (err) {
        message = (err as Error).message
      }
      expect(message, 'the guard must fire').to.match(/at least 16 bytes/)
      expect(message, 'the message must name the observed length').to.match(/4/)
      expect(message.toLowerCase(), 'the message must not embed the secret as hex').to.not.contain('deadbeef')
      expect(message, 'the message must not embed the secret as a JSON array').to.not.contain('222')
    })
  })
})

// ---------------------------------------------------------------------------
// Task 3 — the four negative controls and the D-04 no-leak structural guards
//
// Negative controls are the POINT of this plan, not an afterthought: a round
// trip that only tests the happy path proves almost nothing. Every rejection
// case below asserts its REASON (not merely `ok === false`), and the block
// carries a paired positive control at the end so it cannot pass vacuously
// against an implementation that refuses everything.
// ---------------------------------------------------------------------------

/** The two splits every negative control below is built from. */
const splitA = deriveBootstrapKeys(FROZEN_SECRET)
const splitB = deriveBootstrapKeys(OTHER_SECRET)

/** A valid wrapper over the canary plaintext, sealed under splitA. */
function makeValidWrapper (plaintext: string = CANARY_PLAINTEXT): SealedPayload {
  return sealPayload(plaintext, splitA)
}

/** Rebuild a wrapper with one member replaced. Keeps member order v/nonce/ciphertext. */
function withMember (wrapper: SealedPayload, patch: Record<string, unknown>): Record<string, unknown> {
  return { v: wrapper.v, nonce: wrapper.nonce, ciphertext: wrapper.ciphertext, ...patch }
}

/** Flip the low bit of one byte, re-encode. */
function flipBitAt (b64u: string, index: number): string {
  const bytes = fromBase64url(b64u)
  bytes[index] = bytes[index]! ^ 0x01
  return toBase64url(bytes)
}

const CONTENT_KEY_HEX = Buffer.from(splitA.contentKey).toString('hex')
const CONTENT_KEY_BASE64 = Buffer.from(splitA.contentKey).toString('base64')
const CONTENT_KEY_BASE64URL = Buffer.from(splitA.contentKey).toString('base64url')

describe('bootstrap sealed payload — negative controls and no-leak guards (52-01)', () => {
  // -------------------------------------------------------------------------
  // NC-1 — wrong key (the KEY is the only variable; the AAD is correct)
  // -------------------------------------------------------------------------
  describe('NC-1 — wrong contentKey', () => {
    it('NC-1a: refuses with authentication-failed when only the contentKey differs', () => {
      const wrapper = makeValidWrapper()
      const wrongKeyOnly: BootstrapKeySplit = { lookupId: splitA.lookupId, contentKey: splitB.contentKey }
      const result = unsealPayload(wrapper, wrongKeyOnly)
      expect(result.ok, 'a wrong key must not unseal').to.equal(false)
      if (!result.ok) {
        expect(result.reason, 'a wrong key is an AEAD failure').to.equal('authentication-failed')
      }
    })

    it('NC-1b: the refusal object carries no plaintext member at all', () => {
      const wrongKeyOnly: BootstrapKeySplit = { lookupId: splitA.lookupId, contentKey: splitB.contentKey }
      const result = unsealPayload(makeValidWrapper(), wrongKeyOnly)
      expect('plaintext' in result, 'a refusal must not carry a partial artifact').to.equal(false)
      expect(JSON.stringify(result), 'the refusal must not leak the plaintext canary').to.not.contain(PII_CANARY)
    })
  })

  // -------------------------------------------------------------------------
  // NC-2 — tampered ciphertext (body, tag, truncation)
  // -------------------------------------------------------------------------
  describe('NC-2 — tampered ciphertext', () => {
    it('NC-2a: a single flipped bit in the MESSAGE BODY refuses with authentication-failed', () => {
      const wrapper = makeValidWrapper()
      const tampered = withMember(wrapper, { ciphertext: flipBitAt(wrapper.ciphertext, 0) })
      const result = unsealPayload(tampered, splitA)
      expect(result.ok, 'a body bit-flip must not unseal').to.equal(false)
      if (!result.ok) expect(result.reason, 'a body bit-flip is an AEAD failure').to.equal('authentication-failed')
      expect('plaintext' in result, 'no plaintext on refusal').to.equal(false)
    })

    it('NC-2b: a single flipped bit INSIDE THE 16-BYTE TAG refuses too (the tag is checked, not merely carried)', () => {
      const wrapper = makeValidWrapper()
      const length = fromBase64url(wrapper.ciphertext).length
      const tagByte = length - 8 // strictly inside the trailing 16-byte tag
      expect(tagByte, 'the chosen index must lie inside the tag').to.be.greaterThanOrEqual(length - 16)
      const tampered = withMember(wrapper, { ciphertext: flipBitAt(wrapper.ciphertext, tagByte) })
      const result = unsealPayload(tampered, splitA)
      expect(result.ok, 'a tag bit-flip must not unseal').to.equal(false)
      if (!result.ok) expect(result.reason, 'a tag bit-flip is an AEAD failure').to.equal('authentication-failed')
    })

    it('NC-2c: a ciphertext shorter than the 16-byte tag is refused, not crashed on', () => {
      const wrapper = makeValidWrapper()
      const truncated = withMember(wrapper, { ciphertext: toBase64url(fromBase64url(wrapper.ciphertext).slice(0, 8)) })
      let result: ReturnType<typeof unsealPayload> | undefined
      expect(() => { result = unsealPayload(truncated, splitA) }, 'unsealPayload must never throw').to.not.throw()
      expect(result?.ok, 'a below-tag-length ciphertext must not unseal').to.equal(false)
      if (result !== undefined && !result.ok) {
        // Deliberately the SAME reason as a wrong key: ciphertext length must
        // not be a separately distinguishable oracle (T-52-01-06).
        expect(result.reason, 'truncation shares the single AEAD reason on purpose').to.equal('authentication-failed')
      }
    })

    it('NC-2d: a flipped bit in the NONCE refuses with authentication-failed (nonce is still 12 bytes)', () => {
      const wrapper = makeValidWrapper()
      const tampered = withMember(wrapper, { nonce: flipBitAt(wrapper.nonce, 3) })
      const result = unsealPayload(tampered, splitA)
      expect(result.ok, 'a nonce bit-flip must not unseal').to.equal(false)
      if (!result.ok) expect(result.reason).to.equal('authentication-failed')
    })
  })

  // -------------------------------------------------------------------------
  // NC-3 — wrong AAD (the lookupId is the only variable; the key is correct)
  // -------------------------------------------------------------------------
  describe('NC-3 — wrong AAD (lookupId)', () => {
    it('NC-3a: refuses with authentication-failed when only the lookupId/AAD differs', () => {
      const wrapper = makeValidWrapper()
      const wrongAadOnly: BootstrapKeySplit = { lookupId: splitB.lookupId, contentKey: splitA.contentKey }
      const result = unsealPayload(wrapper, wrongAadOnly)
      expect(result.ok, 'a wrong AAD must not unseal even with the correct key').to.equal(false)
      if (!result.ok) expect(result.reason).to.equal('authentication-failed')
    })

    it('NC-3b: nothing in the refusal carries the original plaintext (this is the failure D-04 AAD binding prevents)', () => {
      const wrongAadOnly: BootstrapKeySplit = { lookupId: splitB.lookupId, contentKey: splitA.contentKey }
      const result = unsealPayload(makeValidWrapper(), wrongAadOnly)
      expect('plaintext' in result, 'delivering a payload under the wrong record identity is the exact failure mode').to.equal(false)
      expect(JSON.stringify(result), 'the refusal must not leak the plaintext canary').to.not.contain(PII_CANARY)
      expect(JSON.stringify(result), 'the refusal must not leak any plaintext fragment').to.not.contain('registrant')
    })

    it('NC-3c: the correct AAD with the correct key still unseals (paired positive control)', () => {
      const result = unsealPayload(makeValidWrapper(), splitA)
      expect(result.ok, 'NC-3 must isolate the AAD, not refuse everything').to.equal(true)
    })
  })

  // -------------------------------------------------------------------------
  // NC-4 — version gate, proven to run BEFORE decryption
  // -------------------------------------------------------------------------
  describe('NC-4 — unknown or malformed version', () => {
    it('NC-4a: v = 2 with a fully correct split reports unsupported-version, NOT authentication-failed', () => {
      const wrapper = makeValidWrapper()
      const result = unsealPayload(withMember(wrapper, { v: 2 }), splitA)
      expect(result.ok, 'an unknown version must be refused').to.equal(false)
      if (!result.ok) {
        expect(result.reason, 'the version gate must run BEFORE decryption').to.equal('unsupported-version')
        // The load-bearing half of this test: with a CORRECT key, an
        // implementation that decrypted first would have succeeded or reported
        // an AEAD failure. Either would prove the ordering wrong.
        expect(result.reason, 'reporting an AEAD failure here would prove decryption ran first').to.not.equal('authentication-failed')
        expect(result.detail, 'the detail names the observed version').to.contain('2')
      }
    })

    it('NC-4b: v = 0 reports unsupported-version', () => {
      const result = unsealPayload(withMember(makeValidWrapper(), { v: 0 }), splitA)
      expect(result.ok).to.equal(false)
      if (!result.ok) expect(result.reason, 'v is a number, just not the locked one').to.equal('unsupported-version')
    })

    it("NC-4c: v = '1' (a string, not a number) reports malformed-wrapper", () => {
      const result = unsealPayload(withMember(makeValidWrapper(), { v: '1' }), splitA)
      expect(result.ok).to.equal(false)
      if (!result.ok) {
        expect(result.reason, 'a wrong-typed v is structural, not a version question').to.equal('malformed-wrapper')
        expect(result.detail, "the detail names the offending member 'v'").to.contain("'v'")
      }
    })

    it('NC-4d: a missing v reports malformed-wrapper naming the member', () => {
      const wrapper = makeValidWrapper()
      const result = unsealPayload({ nonce: wrapper.nonce, ciphertext: wrapper.ciphertext }, splitA)
      expect(result.ok).to.equal(false)
      if (!result.ok) {
        expect(result.reason).to.equal('malformed-wrapper')
        expect(result.detail, "the detail names the missing member 'v'").to.contain("'v'")
      }
    })

    it('NC-4e: v = 1 with the same split unseals (paired positive control for the version gate)', () => {
      const wrapper = makeValidWrapper()
      const result = unsealPayload(withMember(wrapper, { v: SEALED_PAYLOAD_FORMAT_VERSION }), splitA)
      expect(result.ok, 'the version gate must accept the locked version').to.equal(true)
    })
  })

  // -------------------------------------------------------------------------
  // NC-5 — malformed wrappers, with the detail-leak canary scan
  // -------------------------------------------------------------------------
  describe('NC-5 — malformed wrapper', () => {
    const validNonce = 'oKGio6Slpqeoqaqr' // 12 bytes, base64url
    const collectedDetails: string[] = []

    /** Every case: input, the member (or structural fault) its detail must name. */
    function cases (): ReadonlyArray<readonly [string, unknown, string]> {
      const wrapper = makeValidWrapper()
      return [
        ['null', null, 'null'],
        ['a plain string', 'not-a-wrapper', 'object'],
        ['an array', [1, 2, 3], 'array'],
        ['an empty object', {}, "'v'"],
        ['a wrapper missing nonce', { v: 1, ciphertext: wrapper.ciphertext }, "'nonce'"],
        ['a wrapper missing ciphertext', { v: 1, nonce: wrapper.nonce }, "'ciphertext'"],
        ['a nonce decoding to 11 bytes', withMember(wrapper, { nonce: toBase64url(new Uint8Array(11)) }), "'nonce'"],
        ['a nonce decoding to 13 bytes', withMember(wrapper, { nonce: toBase64url(new Uint8Array(13)) }), "'nonce'"],
        ["a nonce containing '+' (standard base64, not base64url)", withMember(wrapper, { nonce: validNonce.slice(0, 14) + '+r' }), "'nonce'"],
        ["a nonce containing '/' (standard base64, not base64url)", withMember(wrapper, { nonce: validNonce.slice(0, 14) + '/r' }), "'nonce'"],
        ["a ciphertext containing '=' padding", withMember(wrapper, { ciphertext: wrapper.ciphertext + '=' }), "'ciphertext'"],
        ['a nonce that is a number, not a string', withMember(wrapper, { nonce: 12 }), "'nonce'"],
        ['a ciphertext that is null, not a string', withMember(wrapper, { ciphertext: null }), "'ciphertext'"]
      ]
    }

    for (const [label, input, mustName] of cases()) {
      it(`NC-5: ${label} refuses with malformed-wrapper, detail naming ${mustName}`, () => {
        let result: ReturnType<typeof unsealPayload> | undefined
        expect(() => { result = unsealPayload(input, splitA) }, 'unsealPayload must never throw').to.not.throw()
        expect(result?.ok, `${label} must be refused`).to.equal(false)
        if (result !== undefined && !result.ok) {
          expect(result.reason, `${label} is a structural fault`).to.equal('malformed-wrapper')
          expect(result.detail, `${label}: detail must name the structural fault`).to.contain(mustName)
          collectedDetails.push(result.detail)
        }
      })
    }

    it('NC-5z: no detail string from any case above contains plaintext, key or ciphertext material', () => {
      expect(collectedDetails.length, 'the scan must have something to scan').to.be.greaterThan(10)
      const wrapper = makeValidWrapper()
      for (const detail of collectedDetails) {
        expect(detail, 'a detail must never carry the plaintext canary').to.not.contain(PII_CANARY)
        expect(detail.toLowerCase(), 'a detail must never carry the contentKey as hex').to.not.contain(CONTENT_KEY_HEX.toLowerCase())
        expect(detail, 'a detail must never carry the contentKey as base64').to.not.contain(CONTENT_KEY_BASE64)
        expect(detail, 'a detail must never carry the contentKey as base64url').to.not.contain(CONTENT_KEY_BASE64URL)
        expect(detail, 'a detail must never quote the ciphertext back').to.not.contain(wrapper.ciphertext.slice(0, 16))
        expect(detail, 'a detail must never carry the lookupId').to.not.contain(splitA.lookupId)
      }
    })

    it('NC-5+: POSITIVE CONTROL — the unmodified wrapper with the correct split still unseals exactly', () => {
      const wrapper = sealPayload(CANARY_PLAINTEXT, splitA)
      const result = unsealPayload(wrapper, splitA)
      expect(result.ok, 'without this the whole negative block could pass vacuously').to.equal(true)
      if (result.ok) expect(result.plaintext).to.equal(CANARY_PLAINTEXT)
    })
  })

  // -------------------------------------------------------------------------
  // G-1 — the contentKey never crosses the wire (D-04's structural guarantee)
  // -------------------------------------------------------------------------
  describe('G-1 — contentKey has no wire form (T-52-01-01)', () => {
    it('G-1a: the wrapper has EXACTLY the members ciphertext, nonce, v (set equality, so a new field fails loudly)', () => {
      const wrapper = sealPayload(CANARY_PLAINTEXT, splitA)
      expect(Object.keys(wrapper).sort(), 'widening the wire silently is the failure this catches').to.deep.equal(['ciphertext', 'nonce', 'v'])
    })

    it('G-1b: JSON.stringify of the wrapper contains the contentKey in NONE of base64url, base64 or hex', () => {
      const serialized = JSON.stringify(sealPayload(CANARY_PLAINTEXT, splitA))
      expect(serialized, 'contentKey must not appear as base64url').to.not.contain(CONTENT_KEY_BASE64URL)
      expect(serialized, 'contentKey must not appear as standard base64').to.not.contain(CONTENT_KEY_BASE64)
      expect(serialized.toLowerCase(), 'contentKey must not appear as lowercase hex').to.not.contain(CONTENT_KEY_HEX.toLowerCase())
      expect(serialized.toUpperCase(), 'contentKey must not appear as uppercase hex').to.not.contain(CONTENT_KEY_HEX.toUpperCase())
    })

    it('G-1c: the lookupId — the half that DOES go to the service — carries none of the contentKey either', () => {
      const serialized = JSON.stringify(deriveBootstrapKeys(FROZEN_SECRET).lookupId)
      expect(serialized, 'lookupId must not embed the contentKey as base64url').to.not.contain(CONTENT_KEY_BASE64URL)
      expect(serialized, 'lookupId must not embed the contentKey as standard base64').to.not.contain(CONTENT_KEY_BASE64)
      expect(serialized.toLowerCase(), 'lookupId must not embed the contentKey as hex').to.not.contain(CONTENT_KEY_HEX.toLowerCase())
    })

    it('G-1d: the contentKey is raw bytes with no string form on the split object', () => {
      const split = deriveBootstrapKeys(FROZEN_SECRET)
      expect(Object.keys(split).sort(), 'the split has exactly two members').to.deep.equal(['contentKey', 'lookupId'])
      expect(split.contentKey, 'contentKey is Uint8Array-only').to.be.instanceOf(Uint8Array)
      expect(typeof split.lookupId, 'lookupId is the only string member').to.equal('string')
    })
  })

  // -------------------------------------------------------------------------
  // G-2 / G-3 — structural source guards
  // -------------------------------------------------------------------------
  describe('G-2/G-3 — source-level structural guards', () => {
    const SRC_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'bootstrap')
    const readSrc = (name: string): string => readFileSync(join(SRC_DIR, name), 'utf8')

    /** Same best-effort stripper as `browser-entry-purity.spec.ts:127-131`. MANDATORY: this module's header names Node builtins deliberately, in prose. */
    function stripComments (src: string): string {
      return src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '')
    }

    it('G-2: the ./bootstrap barrel does not expose the nonce-injecting entry point (but does expose sealPayload)', () => {
      const barrel = readSrc('index.ts')
      // Constructed at runtime so this assertion does not itself put the
      // forbidden symbol name into index.ts's grep-visible neighbours.
      const forbidden = 'sealPayload' + 'WithNonce'
      expect(barrel.includes(forbidden), 'a pinned production nonce must be unreachable through the barrel').to.equal(false)
      expect(barrel, 'paired positive control: the safe entry point IS exported').to.contain('sealPayload')
      expect(barrel, 'the barrel must re-export the key split').to.contain('deriveBootstrapKeys')
      expect(barrel, 'the barrel must re-export the unseal path').to.contain('unsealPayload')
      expect(barrel, 'the re-export must point at this module').to.match(/from '\.\/sealed-payload\.js'/)
    })

    it('G-3a: comment-stripped sealed-payload.ts contains no Node builtin, no byte-buffer type and no CommonJS call', () => {
      const stripped = stripComments(readSrc('sealed-payload.ts'))
      expect(stripped, "no 'node:' specifier").to.not.match(/node:/)
      expect(stripped, "no bare 'crypto'/'fs'/'path'/'buffer' import").to.not.match(/from\s+['"](crypto|fs|path|buffer)['"]/)
      expect(stripped, 'no CommonJS require call').to.not.match(/require\s*\(/)
      expect(stripped, 'no Buffer identifier').to.not.match(/\bBuffer\b/)
      expect(stripped, "no import of '../utils.js' (it drags the Quereus layer into a browser bundle)").to.not.match(/from\s+['"]\.\.\/utils\.js['"]/)
      // Paired positive control: the stripper did not simply erase everything.
      expect(stripped, 'the stripper must leave the real code behind').to.contain('deriveBootstrapKeys')
    })

    it('G-3b: the bare specifiers sealed-payload.ts imports are EXACTLY the pinned five (two-directional set equality)', () => {
      const stripped = stripComments(readSrc('sealed-payload.ts'))
      const found = new Set<string>()
      for (const match of stripped.matchAll(/from\s+['"]([^'"]+)['"]/g)) {
        const specifier = match[1]!
        if (!specifier.startsWith('.')) found.add(specifier)
      }
      const expected = [
        '@noble/ciphers/aes.js',
        '@noble/ciphers/utils.js',
        '@noble/hashes/hmac.js',
        '@noble/hashes/sha2.js',
        '@noble/hashes/utils.js'
      ]
      expect([...found].sort(), 'a later edit reaching for a Node builtin must fail HERE, not at a device cold start').to.deep.equal(expected)
    })
  })
})
