#!/usr/bin/env bash
#
# pin-voter-cert-digest.sh
#
# Purpose : Append a voter release signing-certificate digest to
#           EXPECTED_APP_CERT_SHA256_DIGESTS in
#           apps/VoteTorrentAuthority/src/engines/attestation-keys.generated.ts,
#           and flip the guard test that asserts the release allowlist is empty.
#
#           Dry-run by default: prints the diff and changes nothing. Pass --apply
#           to write. Editing committed attestation config is not something to do
#           by accident.
#
# Usage   : ./scripts/pin-voter-cert-digest.sh <digest> [--apply] [--production]
#
#           <digest>       64 lowercase hex chars, no colons (from read-apk-cert-digest.sh)
#           --apply        actually write the files
#           --production   mark the entry as the production identity rather than
#                          a dev-release TEST identity (default is TEST)
#
# Exit    : 0 — dry-run printed, or files written
#           1 — malformed digest, public debug digest, already pinned, or file drift
#
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

KEYS_FILE="apps/VoteTorrentAuthority/src/engines/attestation-keys.generated.ts"
TEST_FILE="apps/VoteTorrentAuthority/src/engines/__tests__/attestation-keys.releaseGuard.test.ts"
PUBLIC_DEBUG_DIGEST='fac61745dc0903786fb9ede62a962b399f7348f0bb6f899b8332667591033b9c'

DIGEST=""
APPLY=false
PRODUCTION=false

log() { echo "[pin-voter-cert-digest] $*"; }
die() { echo "[pin-voter-cert-digest] ERROR: $*" >&2; exit 1; }

for arg in "$@"; do
  case "${arg}" in
    --apply)      APPLY=true ;;
    --production) PRODUCTION=true ;;
    -*)           die "unknown flag: ${arg}" ;;
    *)            DIGEST="${arg}" ;;
  esac
done

# ── STEP 0: validate the digest ──────────────────────────────────────────────
[ -n "${DIGEST}" ] || die "usage: $0 <digest> [--apply] [--production]"

printf '%s' "${DIGEST}" | grep -qE '^[0-9a-f]{64}$' \
  || die "digest must be exactly 64 lowercase hex characters, no colons.
  Got: '${DIGEST}'
  Normalize with: ./scripts/read-apk-cert-digest.sh <apk>"

if [ "${DIGEST}" = "${PUBLIC_DEBUG_DIGEST}" ]; then
  die "refusing to pin the PUBLIC ANDROID DEBUG certificate.

  Its private key ships in every Android SDK and is committed in this repo. Pinning
  it is the CR-02 defect itself — the guard in attestation-keys.generated.ts exists
  specifically to strip it from release builds."
fi

[ -f "${KEYS_FILE}" ] || die "not found: ${KEYS_FILE}"

if grep -q "${DIGEST}" "${KEYS_FILE}"; then
  die "digest is already pinned in ${KEYS_FILE} — nothing to do."
fi

# ── STEP 1: build the patched files in a scratch dir ─────────────────────────
SCRATCH="$(mktemp -d)"
trap 'rm -rf "${SCRATCH}"' EXIT

if [ "${PRODUCTION}" = true ]; then
  COMMENT=$'\t// Voter release signing certificate (production identity).'
else
  COMMENT=$'\t// DEV-RELEASE TEST IDENTITY -- NOT the production signing certificate.\n\t// Generated by scripts/make-devrelease-keystore.sh for the CR-02 cert-pin\n\t// proof. Remove this entry before shipping, and never treat it as the\n\t// production pin: it is a key the team generated, not the published one.'
fi

# Insert before the closing bracket of the EXPECTED_APP_CERT_SHA256_DIGESTS array.
DIGEST="${DIGEST}" COMMENT="${COMMENT}" node > "${SCRATCH}/keys.ts" <<'NODE'
const fs = require('fs');
const file = 'apps/VoteTorrentAuthority/src/engines/attestation-keys.generated.ts';
const src = fs.readFileSync(file, 'utf-8');

const marker = 'export const EXPECTED_APP_CERT_SHA256_DIGESTS: string[] = [';
const start = src.indexOf(marker);
if (start === -1) {
  console.error('MARKER_NOT_FOUND');
  process.exit(2);
}
const close = src.indexOf('];', start);
if (close === -1) {
  console.error('ARRAY_END_NOT_FOUND');
  process.exit(2);
}

const entry = `${process.env.COMMENT}\n\t'${process.env.DIGEST}',\n`;
process.stdout.write(src.slice(0, close) + entry + src.slice(close));
NODE

# The guard test asserts an EMPTY release allowlist while only the debug digest is
# listed. Once a real digest is pinned, release returns exactly that digest. The
# test carries a comment saying to update it here rather than weaken the guard.
if [ -f "${TEST_FILE}" ]; then
  DIGEST="${DIGEST}" node > "${SCRATCH}/test.ts" <<'NODE'
const fs = require('fs');
const file = 'apps/VoteTorrentAuthority/src/engines/__tests__/attestation-keys.releaseGuard.test.ts';
const src = fs.readFileSync(file, 'utf-8');
const before = 'expect(buildExpectedCertDigests(false)).toEqual([]);';
const after = `expect(buildExpectedCertDigests(false)).toEqual(['${process.env.DIGEST}']);`;
if (!src.includes(before)) {
  console.error('EMPTY_ASSERTION_NOT_FOUND');
  process.exit(2);
}
process.stdout.write(src.replace(before, after));
NODE
fi

# ── STEP 2: show the diff ────────────────────────────────────────────────────
log "proposed change to ${KEYS_FILE}:"
diff -u "${KEYS_FILE}" "${SCRATCH}/keys.ts" || true
if [ -f "${SCRATCH}/test.ts" ]; then
  log "proposed change to ${TEST_FILE}:"
  diff -u "${TEST_FILE}" "${SCRATCH}/test.ts" || true
fi

if [ "${APPLY}" != true ]; then
  log ""
  log "DRY RUN — nothing written. Re-run with --apply to write these changes."
  exit 0
fi

# ── STEP 3: apply ────────────────────────────────────────────────────────────
cp "${SCRATCH}/keys.ts" "${KEYS_FILE}"
[ -f "${SCRATCH}/test.ts" ] && cp "${SCRATCH}/test.ts" "${TEST_FILE}"
log "written."

( cd apps/VoteTorrentAuthority && npx prettier --write \
    src/engines/attestation-keys.generated.ts \
    src/engines/__tests__/attestation-keys.releaseGuard.test.ts >/dev/null 2>&1 ) || true

log "running the guard suite..."
( cd apps/VoteTorrentAuthority && npx jest src/engines/__tests__/attestation-keys.releaseGuard.test.ts )

log ""
log "Pin applied. The release allowlist is no longer empty, so a release build will"
log "now ACCEPT this certificate. If this was a dev-release test identity, that entry"
log "must be removed before shipping."
